### ISSUE TITLE
Vehicles are clipping into the ground

### ISSUE THREAD

**Issue by MinecraftCitiesNetwork** [MinecraftCitiesNetwork/Bugs#1]
- Bord Raptor keeps morphing into the ground
- Only exclusive to CraftyVehicles

**Comment by Technofied** [comment]
I spoke to PM2, they're actively working on a plugin restructure, so hopefully this should be solved soon...

**Comment by Technofied** [comment]
Resolved actually, just waiting on the 1.21 version (thanks @md5sha256!)
