### ISSUE TITLE
/staff-getwool only gives magenta wool 

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#102]
/staff-getwool lime/red/yellow always gives magenta wool anyways

**Comment by VerySmolBirb** [comment]
Just adding on to this that /staff-getsign always gives an oak sign.

**Comment by Technofied** [comment]
How's this going @adamthewarrior ?

**Comment by taylorhaight** [comment]
Just mentioning here that it's also signs = they are all oak.

**Comment by taylorhaight** [comment]
Should be fixed on next restart. TY tech for teaching me the ways of mycommand script :)

**Comment by Technofied** [comment]
All fixed up - taelor pretty much had it bang on,  except MyCommands likes to use "elseif" not "elif",  might have been my bad sorry!
