### ISSUE TITLE
Unknown owner

### ISSUE THREAD

**Issue by HellsideBurnton** [MinecraftCitiesNetwork/Bugs#104]
Apparently the people who owned the cars cant sit on the operator seat. Upon further investigation it turns out that it belongs to "Unknown" Owner
![Screenshot_20240820_200131](https://github.com/user-attachments/assets/6455e9e1-990c-45aa-bf00-baa5b7efbb41)

**Comment by Technofied** [comment]
Once off issue, was with a test build.
