### ISSUE TITLE
New crime scene plugin can grief slabs (not sure about other blocks)

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#108]
![image](https://github.com/user-attachments/assets/e219cbf6-e3a7-4e4a-ae6d-37d36a79c449)

**Comment by crytiee** [comment]
![image](https://github.com/user-attachments/assets/43584624-68f6-421e-94d9-fc52dfc55616)
people caught up ;-;
@Technofied

**Comment by Technofied** [comment]
Fixed this one. :)
