### ISSUE TITLE
Modify Tutorial_Government.yml file to make the "Cabinet" text in the hologram the greenish blue of cabinet roles and such instead of pink

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#11]

**Comment by Technofied** [comment]
Low priority but an annoying bug, feel free to resolve this one. :)

**Comment by adamloeffen** [comment]
Modified line 18 of `home/plugins/DecentHolograms/holograms/Tutorial_Government.yml`
From:`   - content: '&5&lCabinet: &fAppointed players run Government Departments'`
To:`   - content: '&3&lCabinet: &fAppointed players run Government Departments'`

Changed to correct a cosmetic inconsistency where the "Cabinet" text was displaying as pink instead of the typical greenish/blue everywhere else.

**Comment by Technofied** [comment]
Reviewed, looks good to me. I'll be applying this now!
