### ISSUE TITLE
Hunter job doesn't show up in the /jobs menu and doesn't update the prefix.

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#110]
![image](https://github.com/user-attachments/assets/41a89b53-268d-4edc-bc82-d3f43fdc1133)
![image](https://github.com/user-attachments/assets/590ed3ab-4918-4464-98be-f8945271d789)

**Comment by VerySmolBirb** [comment]
![image](https://github.com/user-attachments/assets/be1a5498-af59-491f-aeb8-9c3d5b467a82)
Fixed.
