### ISSUE TITLE
Can't /as delfriend Grxykun or /rg removemember Grxykun from r001

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#111]
The player has been offline for over a year and they can't be removed from the region or areashop. These are the errors I'm getting:
![image](https://github.com/user-attachments/assets/9dcf8584-8f8e-4545-b7c6-2de07c819ba4)
![image](https://github.com/user-attachments/assets/eedc0968-5e16-482d-8cf1-ea97210ab5ba)

**Comment by Technofied** [comment]
Fixed LMAO.
