### ISSUE TITLE
Missing bus

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#113]
There's a missing bus at these coords, Reveille
![image](https://github.com/user-attachments/assets/bd155e15-4dea-4c0f-ad79-cdadea4e5e4a)

**Comment by Nacholebraa** [comment]
The DCT previously had a bus at this location when it was rolled out. I have removed the region from the  area. Should they wish to add it back they will just open a staff ticket and we will adjust it accordingly.
