### ISSUE TITLE
ia problems

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#117]
Just going to list the ongoing problems we're experiencing here.

- custom crops are crafting into random seeds & crates
- Mechanic can't view crafting recipes for vehicles
- Other folks can't see /ia recipes

**Comment by VerySmolBirb** [comment]
I think the last 2 points are fixed now, just the first one.

**Comment by Technofied** [comment]
Should be all solved now. :)
