### ISSUE TITLE
Crime plugin sometimes reports incorrect player as offender in chat

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#119]
![Image](https://github.com/user-attachments/assets/93bf53ef-b543-43a4-a5c5-95c04913b504)

Kvo killed voidOwO here, not a29, the 'no' at the bottom is a29 confirming that they did not hit them at all.

![Image](https://github.com/user-attachments/assets/dfc301f1-9f2c-436a-a110-4afb491679e4)

This in media also shows a29 killing themselves

**Comment by taylorhaight** [comment]
Also doesn't always leave a body and doesn't always come up that someone killed them

**Comment by taylorhaight** [comment]
And sometimes when you respawn, you're invincible

- if you relog it is fixed

**Comment by Technofied** [comment]
Should be resolved now. :)
