### ISSUE TITLE
Prison clinic added to /doctor-attend

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#12]
The DOH created a prison clinic but as of right now, the /doctor-attend command can't teleport any medical staff to it, because it doesn't know the clinic exists. Doctors should be teleported to the coords `4533.5, 73, 2146.5` if a prisoner requires medical attention.

**Comment by adamloeffen** [comment]
### Modified:
- `home/plugins/MyCommand/commands/department_of_health.yml`, inserting the following chunk of code at line 107
```
  - "$Script$%if%%mycommand_playerdatafor_[$arg1]_health_facility%==Reveille Prison Clinic"
  - "%PlayerOptions%teleport: Reveille:4533.5:73.0:2146.5:90.0:0.0"
  - "$RUN_CONSOLE$/mycmd-playerdata removevariable_silent $arg1 health_facility"
```
- Followed the other formats for the code chunk, modifying the coords and the name of the health facility.
- If changes are approved, the player head at `4526, 74, 2147` will need to have the command `/request-a-doctor Reveille Prison Clinic` added to it using mycommand blockset

**Comment by Technofied** [comment]
Great work as always - reviewed and approved. :)
