### ISSUE TITLE
Not getting any money from fishing as a Fisherman

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#120]
Caught like 10 fish with a regular rod and didn't get paid for any of them.

**Comment by Technofied** [comment]
![Image](https://github.com/user-attachments/assets/73ee30de-2947-4d51-ac1f-115d1124a79f)

Should be fixed. Make sure to retake the **exam** (giving the group isn't enough), in order to activate the pay.
