### ISSUE TITLE
/findajob guide links were never updated to new wiki 

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#121]
![image](https://github.com/user-attachments/assets/36f9724f-9c4b-42ba-b539-e2b61dc720f7)

**Comment by crytiee** [comment]
![image](https://github.com/user-attachments/assets/1af1a3fe-701b-4d0a-a669-1d81d880380d)

**Comment by Technofied** [comment]
All up-to-date.
