### ISSUE TITLE
/as info reselling visual bug

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#123]
It shows that all these plots are sold to a player and are reselling
![image](https://github.com/user-attachments/assets/697984fb-c141-4938-83f0-9054ae5c93f0)

**Comment by crytiee** [comment]
I think it'd be less confusing if the line was removed or if it said 'owned by' instead (a player has inquired about this)

**Comment by Technofied** [comment]
I agree with your assessment.

**Comment by Technofied** [comment]
Done!
