### ISSUE TITLE
Orders don't show up on forums and the icon is missing.

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#125]
![image](https://github.com/user-attachments/assets/eb15c499-ba31-464e-818e-03701a943649)
![image](https://github.com/user-attachments/assets/eb15c499-ba31-464e-818e-03701a943649)
![image](https://github.com/user-attachments/assets/f79aa6c0-7fd4-4cb7-86d5-5e2cf09fb581)
![image](https://github.com/user-attachments/assets/f79aa6c0-7fd4-4cb7-86d5-5e2cf09fb581)

**Comment by Technofied** [comment]
Fixed!
