### ISSUE TITLE
The Senior Administrator role on forums is bugged

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#126]
In the 'staff online' tab you just show up as a Citizen. In your posts it gives you both titles: Senior Administrator and Citizen, but when you click on your profile it says 'Administrator'.
![image](https://github.com/user-attachments/assets/8b754aa5-9a45-40af-b6c8-c945bee20eab)
![image](https://github.com/user-attachments/assets/91723b8b-4f9d-4433-9820-8bb5d8ae0917)
![image](https://github.com/user-attachments/assets/6524d3c5-d740-4e14-8ed0-1d7668b819fb)

**Comment by Technofied** [comment]
It's a status you can set yourself here - https://www.democracycraft.net/admin.php?users/crytiee.3689/edit

I've already updated it for you. :)
