### ISSUE TITLE
Possible bedrock issue with custom furniture

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#127]
In some instances bedrock players are unable to destroy certain furniture that they have placed. It shows the 'blood' particles when they try to destroy it and it won't work even for java players when they place it. I had to //cut -e. 
The issue was observed with red oak paint and red wooden sofa middle.

**Comment by crytiee** [comment]
Actually, the only thing that was changed was this: 
![image](https://github.com/user-attachments/assets/65668788-0c4a-4441-88a6-758c4c8c0a0c)
and since it shows blood splatter when they try to break it, I wonder if these are connected somehow.

**Comment by Technofied** [comment]
Not a bedrock issue, some furniture gets bugged and has to be killed by removing the entities. :(
