### ISSUE TITLE
Active playtime dissapearing

### ISSUE THREAD

**Issue by TechsAdminSlave** [MinecraftCitiesNetwork/Bugs#128]
Reported by: JayTheGermanPot
Ticket Number: No ticket was made
Description of Issue: Active playtime seems to be actively dissapearing 
Attach pictures/videos from report: Day before: ![Image](https://github.com/user-attachments/assets/1d15b6d5-0bcd-4d54-88ca-e90c7b549dcc)
Day after: ![Image](https://github.com/user-attachments/assets/fd1385ef-de53-4686-bbf2-84197111a464)

**Comment by Technofied** [comment]
I think this is solved?
