### ISSUE TITLE
Vehicle plugin broken

### ISSUE THREAD

**Issue by TechsAdminSlave** [MinecraftCitiesNetwork/Bugs#129]
Reported by: JayTheGermanPot
Ticket Number: No ticket
Description of Issue: vehicles broken you can literally dissasemble them after placing and cant pick the  up again
Attach pictures/videos from report:![Image](https://github.com/user-attachments/assets/2d206079-c5f6-40c7-b259-721611e21847)
![Image](https://github.com/user-attachments/assets/4e76d2ef-d506-42e3-ad5f-bcd97f985fa5)

**Comment by VerySmolBirb** [comment]
I believe Tech fixed this recently.
