### ISSUE TITLE
WorldEdit ate a player's closet with (I think) art

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#130]
Happened at these coords: 
![image](https://github.com/user-attachments/assets/285d835e-d21b-48db-b523-65a20a725115)

I just did the regular vaulting but then nothing happened on //paste -e or //undo. Tried rollbacking, didn't work. 0 blocks, 0 chunks modified.

**Comment by crytiee** [comment]
Oh actually the problem is that 0 commands from the plugin work as of right now.

**Comment by Technofied** [comment]
WorldEdit has since been fixed.
