### ISSUE TITLE
You can break in to the reveille police station using lockpicks.

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#133]
I think it would make sense if the area past these iron doors would be accessible only to people who have a rank within the DHS, like it is at the hospital. Right now you can break through these doors using lockpicks, accessing the whole DHS police station.
![image](https://github.com/user-attachments/assets/55e57c79-921c-419e-9534-f9b45aa9d140)

**Comment by Technofied** [comment]
Deemed an acceptable risk - it's trespassing. The Department should instead ensure everything sensitive like barrels etc are locked, so theft cannot occur. :)
