### ISSUE TITLE
Windcharge un-afks people

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#137]
Reported by: lcn
Ticket Number: tech-16528
Description of Issue: If you use a wind charge on an /afk player, it moves them, and causes them to not be afk anymore
Attach pictures/videos from report: None

*Note: I have put in an issue on the plugin's GitHub and will be following up on it.

**Comment by taylorhaight** [comment]
https://github.com/EssentialsX/Essentials/issues/5945

**Comment by Technofied** [comment]
Feature works as intended, the fix was pointed out to me by the EssX triage team.

**Comment by Technofied** [comment]
Fixed! :)
