### ISSUE TITLE
Chest Shops cannot include dashes for business names

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#139]
Chest shop not working - "T-T"
![image](https://github.com/user-attachments/assets/b80f0af7-6401-4da2-8944-1fd386a85e39)

Chest shop working fine with a regularly named business. - "Journalism"
![image](https://github.com/user-attachments/assets/ca592763-9d8a-4bd9-9b7d-a61ae4fbd353)

**Comment by Technofied** [comment]
You can now use special characters in chestshops - a previous REGEX limitation. :)
