### ISSUE TITLE
DOS Registration Shoutout Typo

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#14]
The command to request a registration is /dos-requestregistration, but the shoutout says it is /dos-request-registration. Reported by TheReal42Person. ![picture](https://cdn.discordapp.com/attachments/1257154388674351186/1257154389504954509/Screenshot_2024-06-30_at_10.png?ex=66835fc3&is=66820e43&hm=de439f89c0e9801b379868a6ca1a0bd688ca89ba94547d08c8eae5e3ae90d6c4&)

**Comment by adamloeffen** [comment]
### Modified line 143 of `home/plugins/AnnouncerPlus/message-configs/server.conf`
- from
```
"<gradient:#00AAFF:#008EFF><bold>GOV </bold></gradient> <color:#bdc3c7>»</color> <aqua>Remember to register to vote! <color:#008eff>/dos-request-registration!",
```
- to
```
"<gradient:#00AAFF:#008EFF><bold>GOV </bold></gradient> <color:#bdc3c7>»</color> <aqua>Remember to register to vote! <color:#008eff>/dos-requestregistration!",
```

**Comment by Nacholebraa** [comment]
Changes are approved and awaiting server restart.
