### ISSUE TITLE
ImageMaps Despawn - admin-16639

### ISSUE THREAD

**Issue by Nacholebraa** [MinecraftCitiesNetwork/Bugs#140]
Reported by: IzzysaurusRex
Ticket Number: admin-16639
Description of Issue: ImageMaps de-spawning within the museum
![Image](https://github.com/user-attachments/assets/72c41819-eeb6-4712-bd86-fa160f0356b5)

**Comment by Technofied** [comment]
The bulk of it has been fixed,  anything else will have to be replaced on a case by case basis.
