### ISSUE TITLE
Network Issues - tech-16313

### ISSUE THREAD

**Issue by Nacholebraa** [MinecraftCitiesNetwork/Bugs#141]
Reported by: Gamer_top_13
Ticket Number: tech-16313
Description of Issue: Networks are broken again, this time upgrades do absolutely nothing but get consumed, according to /net info which always lists range as 25 and the real world where they just dont work (and have never worked for me). Also none of the container recipes work (but there seems to be a lotta problems with ItemsAdder)
they dont work as in i had spent all the stuff on the upgrades even before the recipes changed and they didnt work multidimensionally, made upgrades again today and it still doesnt work

**Comment by Technofied** [comment]
Resolved
