### ISSUE TITLE
Region Rename - tech-16589

### ISSUE THREAD

**Issue by Nacholebraa** [MinecraftCitiesNetwork/Bugs#142]
Reported by: LCN
Ticket Number: tech-16589
Description of Issue: 

We need to rename a lot of regions

oakstore-XX -> or-store-XX
oakshop-XX -> or-shop-XX
oakapt-XX -> or-apt-XX
oaknews-X -> or-news-XX
oaksp-XX -> or-sp-XX
oaktruck-XX -> or-truck-XX

oak-spawn -> or-spawn
oakhealth -> or-health
oaksheriff -> or-sheriff
oakdepot -> or-depot
oakbrewery -> or-brewery
oakbank -> or-bank

**Comment by Technofied** [comment]
Done :)
