### ISSUE TITLE
Unfine Issue - tech-16427

### ISSUE THREAD

**Issue by Nacholebraa** [MinecraftCitiesNetwork/Bugs#143]
Reported by: The_Superior10
Ticket Number: tech-16427
Description of Issue: Was trying to unfine a previous owner of a plot (tdog444) and it told me their user is invalid so I checked and they did change their name to NoBody22333 when I tired to unfine that the menu opened but when I click on DCT it then tell me I can't unfine them since they didn't join before

![Image](https://github.com/user-attachments/assets/4b0963e6-dc37-421d-bd7a-b05f9386aa2f)
![Image](https://github.com/user-attachments/assets/80dd50a3-540f-4a03-b82d-1705b5821846)

**Comment by Technofied** [comment]
Resolved in ticket with stipulations.
