### ISSUE TITLE
Artmap canvas issue on removal from easel

### ISSUE THREAD

**Issue by Nacholebraa** [MinecraftCitiesNetwork/Bugs#144]
Reported by: EdgiestSteam540
Ticket Number: nacho-16350
Description of Issue: Canvases become useless if taken off of the easel too quickly after being placed
![Image](https://github.com/user-attachments/assets/bbf31dc4-17c3-48f8-984a-4ec7e2746770)

**Comment by Technofied** [comment]
Solved I think
