### ISSUE TITLE
MK-19 Projectile not exploding

### ISSUE THREAD

**Issue by Nacholebraa** [MinecraftCitiesNetwork/Bugs#145]
Reported by: Jabolko
Ticket Number: system-16475
Description of Issue: MK-19 projectiles not exploding

https://cdn.discordapp.com/attachments/1287345110639575082/1287345358816411718/Minecraft__1.21_-_Multiplayer_3rd-party_Server_2024-09-22_11-28-53.mp4?ex=6703018b&is=6701b00b&hm=c3df64ea64aa226968acd2c5217e785c299cdfb18f67c3c3b57b010f57598b70&

**Comment by adamloeffen** [comment]
Ticket resolved in discord
