### ISSUE TITLE
Players are taking damage too quickly from diseases

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#15]
The disease plugin was accidently updated due to a misunderstanding with Taelor and when it was reverted, some of the diseases were left with tick speeds set to damage players very quickly.

**Comment by adamloeffen** [comment]
### Changed the following:

- In 'home/plugins/DemocracyDiseases/diseases.yml`
```
line 96 from "interval: 60" to "interval: 600"
line 243 from "interval: 60" to "interval: 600"
line 276 from "interval: 60" to "interval: 600"
line 337 from "interval: 60" to "interval: 600"
```
Note that other diseases were at 600 which is what I assumed was the correct interval for these diseases were and made the changes accordingly

**Comment by Nacholebraa** [comment]
This change has been approved - looks good.
