### ISSUE TITLE
The enderdragon kill sound is being played in every world and is spammable.

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#150]
You can easily kill ender dragons with guns. People spam this sound and it bothers others, my suggestion would be either limiting it to only the end or disabling it altogether. I have no idea about coding, but I found this, it might be useful: 
![image](https://github.com/user-attachments/assets/3940d26a-725f-402f-aa9e-3560d214949a)

**Comment by Technofied** [comment]
Fixed by setting ``dragon-death-sound-radius`` to 150 in spigot.yml - should mean from where the dragon is killed and 150 block around, people will hear it. Not across worlds.
