### ISSUE TITLE
Player unable to edit/remove roles within a company via /db menu or command.

### ISSUE THREAD

**Issue by Nacholebraa** [MinecraftCitiesNetwork/Bugs#151]
Player: Kvogt2340
Ticket: Adamin-16679
Description: Kvog is reporting they cannot edit the roles within their company. When reveiwing the company menu to see all the roles within the company it shows a million different roles all listed as the same role. I informed her it might be easier for her to delete the company and remake but would opt to have you take a look to ensure it's not just a plugin miswrite.

![Image](https://github.com/user-attachments/assets/7dee8358-706b-49b9-ab5f-d127f59136fe)
![Image](https://github.com/user-attachments/assets/21e9b7f1-f8f6-4d3f-bd94-16133c0d9c0f)

**Comment by Nacholebraa** [comment]
Issue has been forwarded to a developer for further review to confirm if the plugin is miss-writing the information for the company.

**Comment by Technofied** [comment]
Solved, deleted the business via the database. :)
