### ISSUE TITLE
Map missing markers

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#153]
<https://map.democracycraft.net>

A user documented a lot of the bus stops around, and I noticed a few that weren't pinned on the map

Willow, Oakridge, and Aventura don't have their stops set. 
According to the user documented stops there are 4 for Willow and Adventura, and 6 for Oakridge.

I have not verified the below locations, but from the others I checked against the map they should be very close if not dead on.

![image](https://github.com/user-attachments/assets/a4f7695b-5b5d-4d49-a8dd-8e7609f07b7d)

**Comment by Technofied** [comment]
I could really benefit from a Senior/System Administrator giving this a go in adding bus stop markers. :)

**Comment by Technofied** [comment]
Done... 2 months later :P
