### ISSUE TITLE
There are two AK47 guns in the /ia menu. One of them is non-functionial (the one that doesn't show you a recipe for it when you click it)

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#156]
![image](https://github.com/user-attachments/assets/6664bc5b-b7cd-4ee9-8ad2-79d5eeaca3eb)
It doesn't reload and it gets stuck in the aim animation if you left click. (It might be remnants of the old guns, because a player had it)

**Comment by crytiee** [comment]
The gun is also stuck in this aiming position. Tried left clicking again, didn't do anything. 
![image](https://github.com/user-attachments/assets/63f2ee6d-ca99-41ae-b84b-cf33dc120a37)

**Comment by Technofied** [comment]
Fixed up for you. :)
