### ISSUE TITLE
/ticket command formatting

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#16]
All staff /ticket commands are displaying differently then they did before. It's also been reported that no message displays when a staff member claims a ticket.

**Comment by adamloeffen** [comment]
### Modified
`home/plugins/Admin360-Reloaded/config.yml`
- from [old-ticket-config.txt](https://github.com/user-attachments/files/16093167/old-ticket-config.txt)
- to [new-ticket-config.txt](https://github.com/user-attachments/files/16093173/new-ticket-config.txt)

### Footnotes
- github won't let me upload .yml files so .txt was the best I could do
- all I changed was the messages the plugin output when tickets are created/claimed/closed/hpstats to match the old messages before the plugin got all weird

**Comment by Nacholebraa** [comment]
Changes have been **approved**. Please submit the changes. It will be actioned pending the next restart.

**Comment by Technofied** [comment]
Implemented. :)

**Comment by adamloeffen** [comment]
**Issue:** I had to guess originally at some of the lengths of the divider lines ("-------..." <- those things) and some didn't line up correctly... I think I resolved with this newest version of the file (see below text file, as Github won't let me upload a .yml) but not 100% sure as I can't view the tickets as a regular player. I also attached a screenshot of the ticket messages not lining up right so y'all have an example.

![Image](https://github.com/user-attachments/assets/3743e9cc-63d5-4f50-bcf9-288d542cb07e)

[new-ticket-config.txt](https://github.com/user-attachments/files/16489269/new-ticket-config.txt)

**Comment by taylorhaight** [comment]
Are we wanting them to be even on the top and bottom?

![Image](https://github.com/user-attachments/assets/7ac2b792-a7c3-44cb-b613-21f4906b77e6)
![Image](https://github.com/user-attachments/assets/e1154d34-b6f2-472b-b56c-cad25c43d862)

**Comment by adamloeffen** [comment]
Yeah that was the goal... It appears that I counted wrong again 😭

**Comment by taylorhaight** [comment]
Looking great. Thank you, sir! o7
