### ISSUE TITLE
Dino Nugget does not provide instant health as advertised

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#161]
![Image](https://github.com/user-attachments/assets/d4815d9f-b86c-4640-b486-c94070fcc498)
![Image](https://github.com/user-attachments/assets/fc0af4b6-2c18-4320-b243-c74039f5c084)
![Image](https://github.com/user-attachments/assets/fe9f951c-663a-48fa-8fc9-34ec642201f4)

**Comment by VerySmolBirb** [comment]
Provides instant health now, +2 hearts
