### ISSUE TITLE
Cannot analyze clues

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#162]
I got a clue from a case, but when I take it to the terminal it will not process it.
I tried Right click/Left click and while shifting and while not, just in case.

![Image](https://github.com/user-attachments/assets/af888dc4-c11b-41c8-af61-b29a2a68a881)
![Image](https://github.com/user-attachments/assets/763d6c71-b13a-4ff8-9e89-27e11bb4819b)
![Image](https://github.com/user-attachments/assets/eaf4e5c8-42a5-4dd6-9c61-989a2c93006d)
![Image](https://github.com/user-attachments/assets/ef2fedb3-c050-409f-97ce-005818c1b962)

**Comment by Technofied** [comment]
Momentary issue, I reset the database and didn't readd the analysers. :)
