### ISSUE TITLE
Health Plugin Cures Not Working

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#164]
Some players infected with new diseases, Mad Cow was most commonly mentioned, are unable to be cured. Instead, many of them die instantly when given a cure?
- Unsure how to reproduce.
- Ticket Number(s): `system-16872` and `system-16860`

**Comment by Nacholebraa** [comment]
Resolved per techs changelog 10/27/24 [https://discord.com/channels/673612908868927498/825312024866848768/1300274544648654849](url)
