### ISSUE TITLE
murder sometimes blames wrong person (reprise)

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#165]
![Image](https://github.com/user-attachments/assets/b354f94e-5e44-4fca-b6b3-aea21df819e3)
I was standing still at spawn

They said they were killed by a gun.

aa12, m32a1, m4a1s (burst) were the only ones in the players inv, I don't know which was used.

**Comment by Technofied** [comment]
@olzie-12 I can reproduce this again, I can't have this continue to be an issue

**Comment by Technofied** [comment]
Dealt with this one. :)
