### ISSUE TITLE
/medicarepay allows people to pay custom amount

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#166]
`/medicarepay <user> <amount>`

All the treatments are listed and have a set value as far as I'm aware, so regular users shouldn't need access to this, as it would allow for unnecessary, potentially varied, or incorrect payment amounts.

**Comment by Nacholebraa** [comment]
@DrZoddiak  When working on this, all I am finding it opens the GUI when utilizing the format of /medicarepay <username> <amount> and does not issue the custom payment. Could you send a video of what you are doing?

**Comment by DrZoddiak** [comment]
![image](https://github.com/user-attachments/assets/a33c607c-a34f-44b8-9fec-3ae02f78f8a5)

![image](https://github.com/user-attachments/assets/a198af16-cf7c-441d-b006-5e8218b81bca)
Once you verify through the GUI it deducts the amount you've provided. The message even lies and says it takes $25

**Comment by Technofied** [comment]
Hopping on this one, I'm rewriting this

**Comment by Technofied** [comment]
I've rewrote this entirely with /bulkbill. :)
