### ISSUE TITLE
//cut and //cut -e won't actually do anything

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#168]
//cut and //cut -e will say that blocks/entities were affected, but won't actually cut anything.  Same for //copy and //paste.

**Comment by DrZoddiak** [comment]
Just tested in-game, and these appear to be working again!

**Comment by Technofied** [comment]
Sorry about that, there was a brief outage due to Trade interfering. It should be all solved as Dino mentions. :)
