### ISSUE TITLE
Cannot promote users in businesses

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#169]
When trying to promote or demote users the plugin says you cannot pro/demote the owner
![Image](https://github.com/user-attachments/assets/9f7eb40c-a05e-4eb2-ba15-7429113fd4a4)

**Comment by Technofied** [comment]
@olzie-12 latest version causes this, no idea why.

**Comment by Olzie-12** [comment]
I’ll have to take a look, i’m not sure when as i’m travelling this month

**Comment by Olzie-12** [comment]
This should be fixed on the latest commit @Technofied

**Comment by Technofied** [comment]
Yep you're right - resolved!
