### ISSUE TITLE
Can't quit a firm, comes back later

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#170]
![Image](https://github.com/user-attachments/assets/ec796e47-04bc-405e-b01d-7c7c66e822c9)
I've attempted to leave a few companies and they re-appear later, I believe after restarts?

LimbusCompany & "Dinosaur

**Comment by Olzie-12** [comment]
I’ll have to take a look, i’m not sure when as i’m travelling this month

**Comment by Technofied** [comment]
Looks to be resolved now. Thanks Ollie!

**Comment by Technofied** [comment]
god help me

**Comment by DrZoddiak** [comment]
Seems to still be happening. Old jobs that I left before are still there.

![image](https://github.com/user-attachments/assets/c859a01b-4c36-4eca-88cb-e6c8dd5063b3)
![image](https://github.com/user-attachments/assets/a92962d1-c637-4874-8861-5e4b3319e4d3)

**Comment by Technofied** [comment]
@Olzie-12

**Comment by Technofied** [comment]
Done, in future I **can** use SQL to resolve this - but its easier just to try and delete the business.

Deleting it from the business table with foreign key checks on will yell at me and let me know what tables are depending on it.

While role permissions depend on roles - only roles has a direct relationship with business records. It means I also need to hunt the role permissions **first**, delete them, then go back and delete the roles. Then sales and transactions, then I should be able to delete the glitched business record.
