### ISSUE TITLE
drills don't transfer ownership

### ISSUE THREAD

**Issue by aligothz** [MinecraftCitiesNetwork/Bugs#172]
Gold Drills don't transfer ownership properly when dropped for other players.  I suspect the same is true of all drills, but I only tested / validated with gold Drills.

This applied to Drills that have already been used, as well as new ones that are still in crate (generated via /givedrill command)

**Comment by aligothz** [comment]
error message received by player is that they dont have permission

**Comment by VerySmolBirb** [comment]
The player needs to be a miner in order to use any drill. The "owner" of the drill is whoever places it, no transferring of ownership is required.
