### ISSUE TITLE
The tab basically shows vanished players.

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#178]
![Image](https://github.com/user-attachments/assets/d0770906-e809-4130-a72a-6ab7517c2e8a)

**Comment by Technofied** [comment]
![Image](https://github.com/user-attachments/assets/eed63e91-c4df-428d-b581-02bfc9311959)
It might show yourself to you, and other Staff members - but not to players.

(I was vanished)
