### ISSUE TITLE
Legal Qualification in about menu doesn't indicate status

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#179]
![Image](https://github.com/user-attachments/assets/767872b7-c6d0-4a0c-8316-d3cf3c72bb3b)
The legal qualification section doesn't have a Check or X to indicate status

It would be nice to have an at-a-glance status of this in case someone changes their titles.

**Comment by Technofied** [comment]
Fixed up :)
