### ISSUE TITLE
CustomFishing is not registering with LootConomy

### ISSUE THREAD

**Issue by Technofied** [MinecraftCitiesNetwork/Bugs#2]
This means players aren't getting paid when they catch custom fish.

**Comment by Technofied** [comment]
In discussion with LootConomy developer

**Comment by aligothz** [comment]
I believe all jobs are disabled for income except hunter.  If we want the fisherman to get money on catch, we would have to turn that on.

**Comment by aligothz** [comment]
can you provide a little more details as to what it's doing vs what the expected outcome is?

**Comment by Technofied** [comment]
This is an old issue, I need to reassess it with ExcellentJobs to provide more information

**Comment by Technofied** [comment]
Moved to triage, at some stage it'll need to be reviewed but its extremely low priority

**Comment by taylorhaight** [comment]
New: Fisher's don't get money when selling fish to the market with the command /customfishing:sellfish.
I tried and it didn't even recognize the fish. Just an update.

Edit to add there is a plugin update. Can't download as it is premium.

**Comment by Technofied** [comment]
That’s not meant to be on, and please leave it in triage because the original issue needs to be refined

**Comment by DrZoddiak** [comment]
Currently this is still applied to fisherman regularly.

Given the comment above, and the issue from a recent opened ticket the command should probably be disabled.

The permission for Fisherman is set `false` in certain contexts, but true in all others.

but more importantly `customfishing.sellfish` is **default true** meaning **all users** have access to it. Funnily meaning that fisherman are the only restricted group at all! (but not fully)

Edit:
I applied `customfishing.sellfish` `false` to `default` to disable it for now for non-fisherman at the least.

**Comment by aligothz** [comment]
could probably just turn on values for the fish so that fishermen get credit when they catch them, same as hunters get credit on kills.

tell me the values that people should get for fish, and I can add it into the fishermen job so they get paid on catch.

**Comment by Technofied** [comment]
After a very long time (and procrastination) this issue is solved.

ExcellentJobs handles regular fish
Fish Market for custom (accessible at Aventura!) :)
