### ISSUE TITLE
Specific elevator doesn't work when going down

### ISSUE THREAD

**Issue by QuazyOneAndOnly** [MinecraftCitiesNetwork/Bugs#22]
Reported by  @TommysToe

**This is part of a request from Tech to transfer bugs in discord to here. I am NOT involved in this report**

"AnimeInc was trying to put elevators on a plot that only showed up as the "aventura" region

3 elevators were placed, the one in the middle of the bottom and top elevators wasn't recognized, when they moved the elevator to another place on the plot it still had issues

eventually, we removed the middle elevator but then the bottom elevator wasn't recognized as a real elevator (it wasn't showing the number of floors) then when i used the elevator i couldn't go back down, then when the top elevator was supposed to display floor 2 of 2, every time i went up on it, the number would increase and it got all the way to floor 7 out of 7 when it was still only the same two floors

idk what happened i tried checking what could be wrong but it was very broken"

![Image](https://github.com/MinecraftCitiesNetwork/Bugs/assets/136653735/516ee947-632b-43ba-b937-7df400f90d22)

**Comment by taylorhaight** [comment]
In order to move forward on this we need to know the location.

**Comment by taylorhaight** [comment]
I think it was a paste in glitch. I broke down a few blocks, rebuilt up and tadah. it works.
