### ISSUE TITLE
DemocracyDiseases gives players random slowness

### ISSUE THREAD

**Issue by QuazyOneAndOnly** [MinecraftCitiesNetwork/Bugs#23]
Reported by @AdamRC12

**This is part of a request from Tech to transfer bugs in discord to here. I am NOT involved in this report**

"_A_S_H_E_R entered the game extremely slowed without a slowness effect visible. No sickness or status effect. Milk didn't help. First time death fixed the issue. Idk how to recreate."

![Image](https://github.com/MinecraftCitiesNetwork/Bugs/assets/136653735/d796cbbf-e0a3-4039-98e0-14d57639ad98)

**Comment by Technofied** [comment]
Wait completely overlooked what @adamrc12 said, my bad, that seems like a more concrete reason given if it shows in brew info.

How do we replicate this though?

**Comment by Technofied** [comment]
*What @TheReal42Person said, my bad

**Comment by Nacholebraa** [comment]
Tracking and working with the DOH on a resolution. Will provide further updates.

**Comment by Nacholebraa** [comment]
Issue as been resolved. - Duration lowered and clarification issued to #Changelog

**Comment by Nacholebraa** [comment]
Res: Issue was not through DemocracryDiseases - Source: BreweryX. 

See attached for problem / solution.

![Image](https://github.com/user-attachments/assets/29ecbbce-178a-4bcf-ab9a-dd385d2457be)
