### ISSUE TITLE
"Business Shoutout + Staff Reminder Issue"

### ISSUE THREAD

**Issue by QuazyOneAndOnly** [MinecraftCitiesNetwork/Bugs#24]
Reported by @TheReal42Person

**This is part of a request from Tech to transfer bugs in discord to here. I am NOT involved in this report**

"Issue Description: Business shoutouts and Staff Announce things are merging from time to time. Still readable, which is why I marked as low priority."

![Image](https://github.com/MinecraftCitiesNetwork/Bugs/assets/136653735/2c1fe5ae-8047-49a6-9e0f-5d72f8c6de76)

**Comment by Technofied** [comment]
I might have fixed this, need someone to let me know if it still occurs.

**Comment by taylorhaight** [comment]
It's working, but now there are those empty shout outs.

![Image](https://github.com/user-attachments/assets/f3cb78e8-3511-4cb2-9b77-9ff58908f2c1)

**Comment by Nacholebraa** [comment]
> It's working, but now there are those empty shout outs.
> 
> ![Image](https://private-user-images.githubusercontent.com/11755568/350650783-f3cb78e8-3511-4cb2-9b77-9ff58908f2c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NDM1NTMsIm5iZiI6MTcyMTQ0MzI1MywicGF0aCI6Ii8xMTc1NTU2OC8zNTA2NTA3ODMtZjNjYjc4ZTgtMzUxMS00Y2IyLTliNzctOWZmNTg5MDhmMmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDAyNDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYmQxNTA1MWE3MDgzZTcyMjM3NzUyYmY5ZDYzM2Q2OTliZDVjZDU1NGY0NDgxYmRkNWFjNWE3MWNkMzViZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dsq8ucIRlWArY6BaVkzYnlUteWvGdsRDErdM7ffzaX8)

This is not considered an issue rather the government leaving the advertisement blank. It's operating as designed. The government will merely need to update the EO accordingly or off a means to shut it off when not in use.
