### ISSUE TITLE
Error appears when trying to cut entities

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#25]
![Image](https://github.com/MinecraftCitiesNetwork/Bugs/assets/174809393/863173b1-1927-42df-bf05-335a050bcff3)

This error comes up when Hell and I tried to //cut -e and vault the plot at C461.
We tried it multiple times, we waited some time and tried again, still the same error comes up.

**Comment by crytiee** [comment]
same issue happening at C680

**Comment by crytiee** [comment]
after multiple checks we came to the conclusion that the issue is indeed a global one and you can't //cut -e anywhere

**Comment by crytiee** [comment]
after multiple checks it seems like you can't do this on a lot of plots, but in some parts of Reveille the command works.

**Comment by Technofied** [comment]
Please use a more descriptive title, I've edited it for you this time. :)

**Comment by Technofied** [comment]
Fixed!
