### ISSUE TITLE
Adding members to vehicles not working properly

### ISSUE THREAD

**Issue by TheReal42Person** [MinecraftCitiesNetwork/Bugs#28]
When a player added their friend to their car using /vehicle addmember <user>, the other player cannot access the vehicle. Eventually (somehow), they could ride it but were positioned on the roof of the car. I am not sure what exact vehicle this was but another player had this happen with an Ambulance.

**Comment by Technofied** [comment]
MTVehicles is the plugin behind this, we're hoping to retire it in favour of CraftyVehicles.

**Comment by taylorhaight** [comment]
![Image](https://github.com/user-attachments/assets/08c45b86-289c-4e3e-ab52-50e488bb58ec)

Replicable. xD

**Comment by Technofied** [comment]
Won't be an issue with the new plugin. Closing when new plugin is online. :)

**Comment by Technofied** [comment]
Closing in favour for the new plugin. :)
