### ISSUE TITLE
Bedrock players cannot use chest shops.

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#29]
When a bedrock player tries to buy something from a chest shop, it just opens the sign edit menu. When a bedrock player creates a chestshop, it only allows players to open the sign edit menu: it doesn't make an actual shop.

**Comment by taylorhaight** [comment]
https://www.spigotmc.org/wiki/chestshop-faq/#why-does-the-plugin-not-work-with-bedrock-players

**Comment by taylorhaight** [comment]
In order to allow Bedrock accounts with Geyser/floodgate to work you need to adjust two options in your config file:
VALID_PLAYERNAME_REGEXP: "\\.?\\w+$"
This is the regex which usernames need to match. If your prefix for Bedrock usernames is not . then you need to adjust the first . in your regex. (E.g. "\\_?\\w+$" for a _ prefix)
ENSURE_CORRECT_PLAYERID: false
This is necessary so that the UUID type (0) which floodgate uses for Bedrock players is accepted. Please note that disabling that option might result in shops being broken if an admin creates it for a player that has not played before or wasn't cached!
Please note that allowing non-Java accounts with floodgate is experimental and not officially supported and that your economy/money plugin might have issues with non-standard usernames and UUIDs too! For best compatibility enforce global linking of Java accounts with floodgate!

**Comment by Nacholebraa** [comment]
Res: See updated #Changelog for published changes >> https://discord.com/channels/673612908868927498/825312024866848768/1263170596188192790
