### ISSUE TITLE
User received Cholera from drinking alcohol beverage

### ISSUE THREAD

**Issue by aligothz** [MinecraftCitiesNetwork/Bugs#30]
User Luke201556 reported that they received the Cholera debuff from drinking alcohol (beverage not specified at this time) User Zanokuhle also reported receiving the same debuff from Boba tea.

Need to investigate conditions for Cholera debuff and ensure this is expected behavior or if it's an outlier.

**Comment by aligothz** [comment]
user states: "Yo think I found a bug I got Cholera from drinking alcohol, was asked to make a ticket. I was given cholera while drinking "Maple Brew" at a shop/pub."

**Comment by VerySmolBirb** [comment]
This happens due to the cholera chance linked to drinking potions - elixirs are potions so that's why it happens. I wouldn't say it's a bug.

**Comment by aligothz** [comment]
ahhh, I wasn't sure if it was intended behavior or not, so was putting it down as a bug till I had a chance to find out.  Since you say it's intended behavior though, I will close this out.

Thank you Birb! :)
