### ISSUE TITLE
Contradiction in the crates wording on the website

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#31]
On the website: https://democracycraft-store.tebex.io/category/crates#:~:text=Every%20item%20in%20this%20crate%20you%20have%20a%2025%25%20chance%20of%20obtaining!

It says you have a 25% chance of obtaining each item, but you get 1 item per crate, and there's 30 items.

Was reported in a ticket on discord.

**Comment by taylorhaight** [comment]
It's actually on all crate descriptions.

**Comment by Nacholebraa** [comment]
Res: Awaiting resolution requires further assistance. Will publish an update soon.

**Comment by Nacholebraa** [comment]
Res: Issue resolved published update within #Changelog

See attached

![Image](https://github.com/user-attachments/assets/3702e5af-12d8-4d49-8e28-704292fb764d)
