### ISSUE TITLE
DOI Logging Channel + Mail

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#34]
Requested by @TommysToe in his capacity of the Secretary of the DOI

> hi! as the secretary of the DOI i would like to request that we could maybe have a channel where we could see ranger attends like it works in the DOH discord :)
> 
> also if possible, could we maybe create a command so it could mail people about their reported unclaimed build that tells them the coords and date of which they need to make progress on it, it seems like it's possible but could be complicated i just wanted to check <3

**Comment by adamloeffen** [comment]
# Modified:
- Line 34 of home/plugins/MyCommand/commands/department_of_the_interior.yml, inserted 
```  - '$RUN_CONSOLE$/discordsrv:discord broadcast 1264074818991554570 > :horse: **$player is now attending to $arg1!**'```

- Line 179 of home/plugins/MyCommand/commands/department_of_the_interior.yml, inserted
``` ranger-unclaimed: 
  command: /doi-unclaimed
  type: 
  - RUN_COMMAND
  - MINIMESSAGE
  runcmd:
  - '$RUN_CONSOLE$/mail send $arg1 &#00AAFF&lDOI &#bdc3c7&l» &fHey! One of your builds was found unclaimed in the Wild at $arg2 $arg3 $arg4. Please claim it or show progress by $arg5 $arg6 $arg7 or it will be eligible to be removed by the DOI. Thank you!'
  text:
  - '$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» <white>You have successfully sent <#00AAFF>$arg1 <white>an unclaimed build notification!'
  permission-node: democracy.ranger
  permission-required: true
  register: true
  required_args: 7
  tab_completer:
    1:
    - $player_list
    2:
    - X-Coordinate
    3:
    - Y-Coordinate
    4:
    - Z-Coordinate
    5:
    - Month
    6:
    - Day
    7:
    - Year
```

## Footnotes:
- Discord channel ID used in the discordsrv broadcast line
- Added tab completers for what each argument is... not exactly needed but I think will be helpful, especially with so many arguments

**Comment by adamloeffen** [comment]
- line 34 updated to say 
`  - '$RUN_CONSOLE$/discordsrv:discord broadcast 1264074818991554570 > :raccoon: **$player is now attending to $arg1!**'`
because Tommy likes raccoons 🦝

**Comment by Nacholebraa** [comment]
Ive added the server to do a restart later tonight. Please add the changes and post within the #Changelog! Thanks Adam!
