### ISSUE TITLE
Rework Town Permissions

### ISSUE THREAD

**Issue by Technofied** [MinecraftCitiesNetwork/Bugs#35]
The following needs to happen (and are very long overdue):
- The 'Mayor' group needs to go.
- Each Mayor needs their own group prefixed town-mayor
- Resident groups need to be town-resident

Anything else we can think of?

**Comment by Nacholebraa** [comment]
Currently in-progress.

**Comment by Nacholebraa** [comment]
![Image](https://github.com/user-attachments/assets/2b6cdf56-ef15-4dee-a768-d3ef864150be)
