### ISSUE TITLE
Redo Forums Role Syncing

### ISSUE THREAD

**Issue by Technofied** [MinecraftCitiesNetwork/Bugs#36]
Also incredibly (insanely) overdue:
- All job groups need to be in MineSync.
- They need to link to a Forum group, and then the Department group.
- "Secretary" needs to be retired for individual Secretary roles.

**Comment by adamloeffen** [comment]
Actioned + Announced! I'll let system close :>

**Comment by Technofied** [comment]
LETS GO ADAM!! 

You are closing this one >:)

**Comment by adamloeffen** [comment]
💀

Ok xD if I have to...
