### ISSUE TITLE
AFK Kicking

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#38]
Players are no longer getting AFK Kicked after 20 minutes. Had someone come back who had been AFK for 8 hours, and just tested on UnseatedDuke who was AFK 21 minutes without getting kicked.

Also isn't tping to spawn if that was supposed to be a hting.

**Comment by VerySmolBirb** [comment]
Should be solved after server restart.

**Comment by taylorhaight** [comment]
Worked. :)
