### ISSUE TITLE
/doctor-attend broken

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#39]
/doctor-attend isn't working again. It tells the doctors that the person is either already being attended or is not sick (the phrase when someone has already taken it). Set up a temporary warp for now.

**Comment by taylorhaight** [comment]
diseases was turned off until new plugin update per tech.

**Comment by Technofied** [comment]
Ready but on hold, the issue requires the new plugin to be online first. Soon!

**Comment by adamloeffen** [comment]
Appears to be solved, new plugin is back online!
