### ISSUE TITLE
Images not loading on the Wiki

### ISSUE THREAD

**Issue by Technofied** [MinecraftCitiesNetwork/Bugs#4]
This is because when we migrated from Xenforo, the images referenced were from Discord's CDN. 

End >:(

**Comment by Technofied** [comment]
Need to start by identifying all pages with dead images... any volunteers? ;)

**Comment by aligothz** [comment]
if you're talking about the guides, I can certainly go through those, and look for dead images.  if it's just a matter of taking screenshots of things that are in /ie (I think it is) then, I can do that as well.  Some of them though, like the large brewer barrels, I know aren't on the guide, or in ie.  But, can start in the guides, identify what's missing, and then go from there.

**Comment by Nacholebraa** [comment]
> if you're talking about the guides, I can certainly go through those, and look for dead images. if it's just a matter of taking screenshots of things that are in /ie (I think it is) then, I can do that as well. Some of them though, like the large brewer barrels, I know aren't on the guide, or in ie. But, can start in the guides, identify what's missing, and then go from there.

Yes, they are referring to existing images throughout the guides. Current newer ones are fixed but the older ones are still broken.

**Comment by DrZoddiak** [comment]
I compiled a list of ones that are visually not loading. 
This list does **not** account for links that are broken, but still cached.

[One example of that would be lumberjack](https://wiki.democracycraft.net/jobs/trades/lumberjack)
Which according to the below table suggests only 1 broken link, when in reality it's actually two. One is just cached (somewhere).

[This is the cached link](https://i.imgur.com/tzWfNL8.png)
It loads a 404 if you attempt to load it, but as you can see on the wiki, it's still there.

That is all to say that this is the current list of dead image links, but it's possible more images will die if/when that cache refreshes.

| File | Info from link | Closest Linkable Section |
| --- | --- | ---|
|staffintent         | revville_borders-png       | https://wiki.democracycraft.net/policies/staffintent#preservation-of-aesthetic|
|staffvetos          | img.png		                 | https://wiki.democracycraft.net/policies/staffvetos#city-design|
|accountant          | 2023-10-23_21.30.46        | https://wiki.democracycraft.net/jobs/trades/accountant|
|contractor          | 2022-11-08_19.02.59        | https://wiki.democracycraft.net/jobs/trades/contractor|
|designer            | 2022-11-12_00.14.26        | https://wiki.democracycraft.net/jobs/trades/designer|
|designer            | 2023-07-24_00.44.46        | https://wiki.democracycraft.net/jobs/trades/designer#painting|
|designer            | N/A		                 | 9 additional instances throughout|
|farmer              | 2022-11-13_22.13.15        | https://wiki.democracycraft.net/jobs/trades/farmer|
|farmer              | capture-png                | https://wiki.democracycraft.net/jobs/trades/farmer#passed-the-exam-what-now|
|fisherman           | 2022-11-13_22.24.57        | https://wiki.democracycraft.net/jobs/trades/fisherman|
|hunter              | 2023-11-04_20.55.08_4      | https://wiki.democracycraft.net/jobs/trades/hunter|
|journalist          | 2023-10-23_22.21.23        | https://wiki.democracycraft.net/jobs/trades/journalist|
|lumberjack          | 2023-03-12_18.10.35        | https://wiki.democracycraft.net/jobs/trades/lumberjack|
|miner               | 2021-08-06_00.17.56        | https://wiki.democracycraft.net/jobs/trades/miner|
|miner               | calcite-png	               | https://wiki.democracycraft.net/jobs/trades/miner#miner-recipes|
|economist           | 2023-03-12_17.33.28        | https://wiki.democracycraft.net/government/departments/commerce/jobs/economist|
|economist           | 2022-06-18_18.39.04        | https://wiki.democracycraft.net/government/departments/commerce/jobs/economist#structure|
|buildinginspector   | 2022-06-18_18.36.26        | https://wiki.democracycraft.net/government/departments/construction-and-transportation/jobs/buildinginspector|
|buildinginspector   | 2022-06-17_00.53.55        | https://wiki.democracycraft.net/government/departments/construction-and-transportation/jobs/buildinginspector#activity |
|constructor         | 2022-09-17_19.13.23        | https://wiki.democracycraft.net/government/departments/construction-and-transportation/jobs/constructor|
|constructor         | 2023-03-12_18.16.14        | https://wiki.democracycraft.net/government/departments/construction-and-transportation/jobs/constructor#structure|
|archivist           | 2022-10-28_22.23.30        | https://wiki.democracycraft.net/government/departments/education/jobs/archivist/|
|archivist           | 2022-10-28_02.56.44        | https://wiki.democracycraft.net/government/departments/education/jobs/archivist/#methodology-for-research-and-article-creation|
|guide               | 2023-11-05_00.35.54        | https://wiki.democracycraft.net/government/departments/education/jobs/guide|
|guide               | 2022-11-15_11-50-06        | https://wiki.democracycraft.net/government/departments/education/jobs/guide#route|
|professor           | School_render_unedited     | https://wiki.democracycraft.net/government/departments/education/jobs/professor|
|medicalspecialist   | 2023-10-21_13.37.14        | https://wiki.democracycraft.net/government/departments/health/jobs/medicalspecialist|
|medicalspecialist   | 2022-09-27_15.57.15        | https://wiki.democracycraft.net/government/departments/health/jobs/medicalspecialist#structure|
|paramedic           | 2022-09-27_15.57.15        | https://wiki.democracycraft.net/government/departments/health/jobs/paramedic|
|paramedic           | image0.png                 | https://wiki.democracycraft.net/government/departments/health/jobs/paramedic#procedure|
|ranger              | 2021-04-25_01.25.15        | https://wiki.democracycraft.net/government/departments/interior/jobs/ranger|
|ranger              | 2022-09-23_20.54.01        | https://wiki.democracycraft.net/government/departments/interior/jobs/ranger#structure|
|police              | 2023-03-12_16.02.17_2      | https://wiki.democracycraft.net/government/departments/justice/jobs/policeofficer|
|police              | 2023-03-12_18.13.49        | https://wiki.democracycraft.net/government/departments/justice/jobs/policeofficer#structure|
|stateprosecutor     | 2022-07-30_22              | https://wiki.democracycraft.net/government/departments/legal-affairs/jobs/stateprosecutor|
|eventofficer        | 2021-04-25_01.27.56        | https://wiki.democracycraft.net/government/departments/public-affairs/jobs/eventofficer|
|eventofficer        | 2021-02-15_12.12.01        | https://wiki.democracycraft.net/government/departments/public-affairs/jobs/eventofficer#structure|
|mediaofficer        | social-media-opportunities | https://wiki.democracycraft.net/government/departments/public-affairs/jobs/mediaofficer|
|auditor             | 2023-10-23_21.30.46        | https://wiki.democracycraft.net/government/departments/state/jobs/auditor|
|electionofficer     | 2022-06-17_00.38.35        | https://wiki.democracycraft.net/government/departments/state/jobs/electionofficer|
|electionofficer     | 2022-06-17_00.41.18        | https://wiki.democracycraft.net/government/departments/state/jobs/electionofficer#structure|
|politics            | 2021-02-15_12.15.42        | https://wiki.democracycraft.net/government/politics|
|politics            | 2021-02-14_15.04.32        | https://wiki.democracycraft.net/government/politics#elected-positions|
|branding            | Seal_DLA                   | https://wiki.democracycraft.net/government/branding#executive|
|reveille            | Reveille   x16             | https://wiki.democracycraft.net/history/reveille|
|newbeginnings       | (active youtube link)      | https://wiki.democracycraft.net/history/newbeginnings#dc-premiers-on-youtube|
|endeavor            | Presidential_portrait_end  | https://wiki.democracycraft.net/history/executive/former-admin/endeavour|

**Comment by Technofied** [comment]
This is a Christmas wish come true!! Thank you so much @DrZoddiak <3

**Comment by DrZoddiak** [comment]
The new wiki has a way of tracking this, as well.

https://wiki.democracycraft.net/Category:Pages_with_broken_file_links

If someone wanted to take up the file uploads <https://wiki.democracycraft.net/Special:Upload> can be used to do so.

The link on the page will also need to be updated to use the new file.

Spaces are fine in the name : `_` and ` ` are the interchangeable on the wiki, so no worries.

If you use it in the wiki - `[[File:imgname.png]]`
