### ISSUE TITLE
Canceling "Send Parcel" deletes the item

### ISSUE THREAD

**Issue by QuazyOneAndOnly** [MinecraftCitiesNetwork/Bugs#41]
When you're at the the Post office and right click the NPC and click the option of sending a parcel you can put items in the opened menu and you have 2 buttons, Send and Cancel. When an item in inside the menu and you hit "Cancel" the item is still destroyed.

**Comment by Technofied** [comment]
Oh dear, @md5sha256 will take a look at this

**Comment by md5sha256** [comment]
I thought this was fixed recently?

**Comment by md5sha256** [comment]
Yeah i cannot repro this on prod, im pretty sure this was fixed.

**Comment by taylorhaight** [comment]
> Yeah i cannot repro this on prod, im pretty sure this was fixed.

You're correct this has been fixed. :)
