### ISSUE TITLE
Minecraft vanilla commands are taking preference over plugin commands

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#45]
/msg gives people a different message than our custom one. Tech is talking to dev about it.

![Image](https://github.com/user-attachments/assets/d0109e5c-1003-4b12-999e-281c450e99b8)

EDIT: Applies to /mute too

**Comment by Technofied** [comment]
This along with /mute and other commands, which exist in Minecraft vanilla, seem to be taking preference over plugin defined commands.

Unfortunately nothing we can do until [this Issue](https://github.com/PaperMC/Paper/issues/11035) is resolved

**Comment by Technofied** [comment]
/mute was a different conflict, so I fixed that one.

**Comment by Technofied** [comment]
Thankfully fixed now with jmp's Paper PR!
