### ISSUE TITLE
Brewers unable to open book of brews

### ISSUE THREAD

**Issue by aligothz** [MinecraftCitiesNetwork/Bugs#47]
Brewers are unable to open book of brews, it just sits there and you can't interact with it.

Suspect it may be a permissions issue, but not sure

**Comment by Technofied** [comment]
Got a hunch this is to do with Minecraft redoing itemstack stuff again :/

**Comment by Technofied** [comment]
Fixed this one :)

**Comment by aligothz** [comment]
out of curiosity, how did you fix this?

**Comment by Technofied** [comment]
> out of curiosity, how did you fix this?

The Recipes book is a BreweryX Addon, it was several versions dated. I'm honestly sorta confused how that wasn't caught - but at least it got caught now. :)
