### ISSUE TITLE
/skills not working

### ISSUE THREAD

**Issue by aligothz** [MinecraftCitiesNetwork/Bugs#49]

**Comment by aligothz** [comment]
/skills command doesn't work.

added an alias in commands.yml to try and restore function:
  skills:
  - skillsmanager

waiting on server restart to see if change takes effect

**Comment by Technofied** [comment]
Valid resolution, ExcellentJobs is a little bit quirky in the sense that we can just define it as a command of the plugin instead though - so I've just tweaked it to do that now. If it was virtually any other plugin though, what you did is what I'd do :)

Check out line 8 on plugins/ExcellentJobs/config.yml when you get the chance :D

**Comment by aligothz** [comment]
ahhhhh, so it's got the same thing built into it as what I was doing to fix it.

are there a lot of plugins that are like that?

**Comment by aligothz** [comment]
removed skillsmanager alias in Command.yml since functionality was restored via plugin.

**Comment by Technofied** [comment]
> ahhhhh, so it's got the same thing built into it as what I was doing to fix it.
> 
> are there a lot of plugins that are like that?
Unfortunately (or fortunately?) no

**Comment by Technofied** [comment]
> removed skillsmanager alias in Command.yml since functionality was restored via plugin.

Cheers!
