### ISSUE TITLE
IA Items aren't showing their custom texture on chest shop holograms

### ISSUE THREAD

**Issue by AdamRC12** [MinecraftCitiesNetwork/Bugs#50]
![Image](https://github.com/user-attachments/assets/a9958693-43e8-4d41-aacd-1003ef5024e0)

**Comment by taylorhaight** [comment]
Texture pack needs refreshed through cloudflare. I tried in my channel but needed help.

Edit to add it's that way with all IA items.

**Comment by Technofied** [comment]
> Texture pack needs refreshed through cloudflare. I tried in my channel but needed help.
> 
> Edit to add it's that way with all IA items.

The issue is not to do with textures. Speaking to Olzie to determine if its holograms or trade to blame

**Comment by Technofied** [comment]
LoneDev is away at the moment, so this will take a while longer for it to be solved.

**Comment by Technofied** [comment]
Fixed! Nothing to do with IA, everything to do with holograms. Yipee!
