### ISSUE TITLE
Crafting Issues - Arctic_Fox10

### ISSUE THREAD

**Issue by Nacholebraa** [MinecraftCitiesNetwork/Bugs#51]
Player Reported Issue
> Hey sorry to bother you with the new update bugs, but I just want to let you know that /craft is wack right now. For example, I can't craft planks without clicking the recipe book and I think it duplicates the planks as well. I understand that this is a huge update, so I just wanted to let you know. Tysm for updating the server

**Comment by Technofied** [comment]
Should be fixed as of a few days ago, open a new report with more details to reproduce if it crops up again. Thanks! :)
