### ISSUE TITLE
wither skeletons refuse to be captured

### ISSUE THREAD

**Issue by aligothz** [MinecraftCitiesNetwork/Bugs#55]
Wither skeletons appear to be capturable by hunters.  They charge the hunter for the capture, but refuse to go into the egg.

I was able to recreate as well.

checked in mobstoeggs, wither skeletons are set to be able to be captured, and checked in luckyperms, and it seems like hunters have permissions to capture them.

mobs to eggs plugin is at version 1.7.11, with a 1.7.12 version being available as of 7/22/24.  I don't however see any mention of wither skeleton fix in patch notes, so doubtful an upgrade would resolve the problem.

![Image](https://github.com/user-attachments/assets/4071a5da-e9b0-4d82-af43-e2f6941c05b0)

![Image](https://github.com/user-attachments/assets/b7058110-3142-4a5d-817f-bae49a30cf3e)

**Comment by Technofied** [comment]
It's worth updating regardless, a lot of the time developers make silent fixes or unintentionally fix issues like this :)

**Comment by Technofied** [comment]
Fixed now... I don't know how but yay! :)
