### ISSUE TITLE
network tier 4 not working

### ISSUE THREAD

**Issue by aligothz** [MinecraftCitiesNetwork/Bugs#56]
Networks don't seem to want to upgrade to Tier4.

My understanding of networks is that there are 4 tiers with the following benifits
Tier 0 - range 25
Tier 1 - Range 50
Tier 2 - Range 200
Tier 3 - range 500 
Tier 4 - works across dimensions.

This is largely based on the documentaiton at: https://wiki.democracycraft.net/features/networks/

I have a network that I never upgraded to T4, but when I tried to apply the upgrade to it, was being told it's already at max lvl.

![Image](https://github.com/user-attachments/assets/cc9e04db-dd6c-4c56-87c6-a868e46b86f2)

![Image](https://github.com/user-attachments/assets/520f6525-426b-419a-b616-c5d4cf597ee7)

**Comment by Technofied** [comment]
@aligothz Do you mind seeing if this is still the case? (You can try /thru or spectate then gms into the staff room below spawn, then grab a tier 4 upgrade and trying to apply it)

**Comment by Technofied** [comment]
Fixed! (confirmed from my testing)
