### ISSUE TITLE
Cosmetic Abuse

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#61]
> Was using the elder guardian morph cosmetic and when I stopped using it I could still fly like I had creative
reported by @Aladeen

**Comment by adamloeffen** [comment]
My quick fix was to disable that cosmetic until we can find a long term solution.
Edited line 160 of `home/plugins/ProCosmetics/morphs.yml`
- from: `      enable: true`
- to: `      enable: false`

**Comment by adamloeffen** [comment]
Another user opened a system ticket about abuse for another morph so I reversed the above and instead did the following

Modified line 2 in home/plugins/ProCosmetics/morphs.yml
- From: `  enable: true`
- To: `  enable: false`

**Comment by Technofied** [comment]
Based on the timestamps of your comments, I'm pretty sure I fixed this. IF there's any more reports, refile the issue :D
