### ISSUE TITLE
MS Hospital Warps

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#63]
The Secretary of Health requests that a command be set up for MS+ allowing them to teleport to the different DOH sites without a patient requesting care. Would be useful for trainings and also restocking the different sites.

(Note: I'm happy to do it, I want to make it a DeluxeMenu, just want to make sure the idea is approved first)

**Comment by Technofied** [comment]
Approved :)

**Comment by Technofied** [comment]
Oh ok it was done in August, oops!!
