### ISSUE TITLE
IA Crafting Dupes

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#65]
When one tries to craft an item from IA and they do it in bulk (more than 1 item at a time), it gives them an infinite amount of some items.

**Comment by taylorhaight** [comment]
Should we just disable this for now?

**Comment by taylorhaight** [comment]
So far chefs and masons have reported.

**Comment by Technofied** [comment]
Fixed this!

> Should we just disable this for now?

Feel free to @ me on any of these issues to get a response, I apologise for not seeing this earlier
