### ISSUE TITLE
Old DHS name issue with chat toggle

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#66]
![Image](https://github.com/user-attachments/assets/e555a784-b5b6-4a69-9e74-0128093eea0f)

Toggling to dhs chat with the /dhs command will show you 'You are now messaging department_of_justice' message, instead of 'You are now messaging department_of_homeland_security'

**Comment by Technofied** [comment]
Thank you for reporting! I've fixed this, should be effective from **next restart.**

If there are issues in the mean time with channel access, that too will be solved next restart. :)
