### ISSUE TITLE
Jail sign lifts the handcuffs

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#68]
When you click this sign to jail someone it automatically lifts the handcuffs off of them allowing them to escape or teleport away.

![Image](https://github.com/user-attachments/assets/355d53d5-9fb1-4478-9e21-5c332639116b)

**Comment by Technofied** [comment]
I'm not sure how this is an issue @crytiee , given if they do run away they get jailed by the time the officer interacts with the GUI (?)

Feel free to let me know if I'm wrong though, I'm just not sure if this is an issue

**Comment by crytiee** [comment]
So the problem is whenever you click on the sign it immadiately lifts their handcuffs. To jail them you have to select the emerald block. If you are ultra fast it is possible right now but if someone has a lot of wanted points (situation from today) then it will ask you how much you'd like to extend their punishment. 
So 
1. you press the sign
2. their handcuffs are immadiately lifted
3. you press the emerald block
4. the GUI closing animation needs to finish
5. the plugin asks you how much you want to extend their jailtime
6. now you have to write in chat a number
Between steps 3-6 you have no time to react and criminals can easily abuse this to just elytra away.
@Technofied

**Comment by Technofied** [comment]
I still fail to see the issue @crytiee because once you input the duration of their sentence, they get sent to jail if that makes sense. That’s why I think it’s more of a visual/inconvenience issue if that makes sense

**Comment by crytiee** [comment]
Well sometimes it asks to input the time sometimes it doesn't and it seems to be random because it both happens or doesn't happen for people who commit multiple murders but that's another issue. It's not only a visual inconvenience because as soon as you press the sign the other person can /spawn or kill you or fly away. If you can navigate the UI in and input the time in less than a second then it's not a problem, but the other player can just spam rockets/gun/tp command. If they choose to escape and not kill you and you input the time when they already flied off/tp'd away then they won't get send to jail anyways.

**Comment by Technofied** [comment]
Won't be an issue with the new Crime plugin (due to how jailing works), I'll keep it open for a bit though - until we transition that is. :)
