### ISSUE TITLE
New potions not working

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#71]
Potion of Oozing, Potion of Weaving and Potion of Windcharge are not executing their death action.

Oozing is supposed to spawn some baby slimes if you die while under the influence of the potion.
Weaving is supposed to spawn spider webs if you die
and Windcharge is supposed to burst out a blast of air if you die.

No errors in console nor in game.

Tested in both wilderness and main world.

**Comment by taylorhaight** [comment]
Wonder if it's due to death spectating.

**Comment by Technofied** [comment]
> Wonder if it's due to death spectating.

Spot on actually, a developer will need to take a look. It's an incredibly low priority though (given this is mostly a cosmetic thing)

**Comment by Technofied** [comment]
Fixed up :)
