### ISSUE TITLE
Name/Color Glitch

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#73]
Specifically only happens in Mod chat (`/m`) but I figured I'd report incase it's happening to anyone else... low priority.

When I type in general, local, or send a message my name color stays the default grey as shown below:
![Image](https://github.com/user-attachments/assets/60611c38-d4a6-4a1f-8d78-9543562ff1ae)

When I talk in Mod chat, my name becomes my prefix color:
![Image](https://github.com/user-attachments/assets/5e28ccb3-5f5f-47b4-97aa-eecf9bbcefe7)

**Comment by Technofied** [comment]
Isuse found and solved. :)
