### ISSUE TITLE
Post Office NPC bug

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#74]
(see linked video)
https://drive.google.com/file/d/1Ls5A3EUzRMIgkWSQpsQcYRgidudNWoCs/view?usp=sharing

**Comment by taylorhaight** [comment]
This is with all npcs at least for staff.
When right clicking an NPC, you're able to mount them.

Working on this.

**Comment by taylorhaight** [comment]
Fixed! Twas in Gsit.
