### ISSUE TITLE
/ia get doesn't work for custom NBT items

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#77]
**Issue:** When admin+ uses the ia menu, there should be an option to save any item who's recipe your viewing straight to your inventory. I'm assuming this is a 1.21 issue again, but as of now the option exists but can't be used. It is no longer colored the way it should be and yields no output when selected. See below picture for details regarding the coloring of the save icon's name.

![Image](https://github.com/user-attachments/assets/dd030a77-734a-4f77-a2bf-45dbfa1af370)

**Comment by taylorhaight** [comment]
Updating: Mechanic recipes (all), guns (all except lightsabers), Book o Brews

**Comment by Technofied** [comment]
Will be a while to fix this one. LoneDev is away. :(

This only applies to items with custom NBTs, so not all thankfully.

**Comment by Technofied** [comment]
Fixed! Woohoo!
