### ISSUE TITLE
Players can see chat bubbles from others they have /ignore'd

### ISSUE THREAD

**Issue by Technofied** [MinecraftCitiesNetwork/Bugs#8]
See title. Someone needs to start discussing with the developer of CustomNameplates on how to fix this. :)

**Comment by Technofied** [comment]
Need's a PR to CustomNameplates or CarbonChat, or both, not sure when we can get to this

**Comment by Technofied** [comment]
I've attached @DrZoddiak to this, they're working quite hard in getting this resolved. :)

**Comment by DrZoddiak** [comment]
Just going to link this here for posterity <https://github.com/DrZoddiak/Custom-Nameplates>
This is the current fork that contains the changes I've made so far.

As of <https://github.com/DrZoddiak/Custom-Nameplates/commit/2cc734fc9ddcbc0548b514bebe49ea6bde28e439> this issue should be fully resolved.

Additionally, the issues surrounding the `channel-type` config options have also been resolved.
That issue being that the other two config options simply did not work at all.

and those fixes are <https://github.com/DrZoddiak/Custom-Nameplates/commit/c356bd08b4809dba71b578a47ca39704b00dc49c> and <https://github.com/DrZoddiak/Custom-Nameplates/commit/30e2417f33943c1d89dc88a89ce80bac28e604b7>

Awaiting confirmation/verification of fixes before closing.

**Comment by Technofied** [comment]
> Just going to link this here for posterity https://github.com/DrZoddiak/Custom-Nameplates This is the current fork that contains the changes I've made so far.
> 
> As of [DrZoddiak/Custom-Nameplates@2cc734f](https://github.com/DrZoddiak/Custom-Nameplates/commit/2cc734fc9ddcbc0548b514bebe49ea6bde28e439) this issue should be fully resolved.
> 
> Additionally, the issues surrounding the `channel-type` config options have also been resolved. That issue being that the other two config options simply did not work at all.
> 
> and those fixes are [DrZoddiak/Custom-Nameplates@c356bd0](https://github.com/DrZoddiak/Custom-Nameplates/commit/c356bd08b4809dba71b578a47ca39704b00dc49c) and [DrZoddiak/Custom-Nameplates@30e2417](https://github.com/DrZoddiak/Custom-Nameplates/commit/30e2417f33943c1d89dc88a89ce80bac28e604b7)
> 
> Awaiting confirmation/verification of fixes before closing.

Fixed, the honour is yours to close. :)

**Comment by DrZoddiak** [comment]
Issue resolved. Thanks for the honors :)
