### ISSUE TITLE
Wither Missile Dupe

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#80]
Player reported using the wither missile from cosmetics > gadgets gives unlimited wither skeleton skulls. 

This gadget has been disabled until it can be fixed.

I've attached the video they shared.
https://drive.google.com/file/d/1YmlaQbxFdXlHnfnWY_NR84uincGtDQqr/view?usp=sharing

**Comment by Technofied** [comment]
Solved somewhat given we migrated to a new plugin
