### ISSUE TITLE
Dead Links on Wiki

### ISSUE THREAD

**Issue by DrZoddiak** [MinecraftCitiesNetwork/Bugs#83]
Below is a list of resources that are dead links.

Headers represent where they are inside of the wiki.
ex. `#Welcome - ## Making Money` Are apart of the same section, and the link that needs tending will be found under "Making money"

Discord links have been denoted with their intended paths

___

# Welcome

## Making money

https://www.democracycraft.net/threads/making-money.1410/

## Chest Shops

https://www.democracycraft.net/threads/chest-shops.76/

## Jobs & Exams

https://www.democracycraft.net/threads/jobs.711/

https://www.democracycraft.net/forums/job-guides.50/

## Chat

https://www.democracycraft.net/threads/commands.1264/

___

# Jobs / Professions

### Making money

https://www.democracycraft.net/threads/chest-shops.76/

// DC Jobs Server
https://discord.com/invite/Q8rNjddjjh

https://www.democracycraft.net/threads/making-money.1410/

### General Links

// RBA
https://discord.com/invite/U6gtx7Kqbh

### Passed the Exam

https://www.democracycraft.net/threads/making-money.1410/

// DC JOBS
https://discord.com/invite/Q8rNjddjjh

### What to do after passing

https://www.democracycraft.net/threads/making-money.1410/

### Passed the Exam

https://www.democracycraft.net/threads/making-money.1410/

// DC JOBS
https://discord.com/invite/Q8rNjddjjh

# Jobs / Trades

### Passed the Exam

https://www.democracycraft.net/threads/making-money.1410/

// DC JOBS
https://discord.com/invite/Q8rNjddjjh

### After Passing the exam

https://www.democracycraft.net/threads/making-money.1410/

// DC JOBS
https://discord.com/invite/Q8rNjddjjh

### Passed the exam

// DC JOBS
https://discord.com/invite/Q8rNjddjjh

### Passed the Exam

// DC JOBS
https://discord.com/invite/Q8rNjddjjh

### Passed the Exam

https://www.democracycraft.net/threads/making-money.1410/

https://www.democracycraft.net/threads/mob-egg-capturing.9644/

### Passed the Exam

https://www.democracycraft.net/threads/making-money.1410/

// DC JOBS
https://discord.com/invite/Q8rNjddjjh

### Passed the Exam

https://www.democracycraft.net/threads/making-money.1410/

// DC JOBS
https://discord.com/invite/Q8rNjddjjh

### Passed the Exam

https://www.democracycraft.net/threads/making-money.1410/

// DC JOBS
https://discord.com/invite/Q8rNjddjjh

# Government / Departments / Construction & Transportation / Jobs

### Application Process

https://www.democracycraft.net/threads/application-information.8/

# Government / Departments / Legal affairs / Jobs

## Protocols

https://www.democracycraft.net/threads/employment-policy.11761/

# Government / Exchanges

## Where Can I find stock exchanges

// The Exchange
https://discord.com/invite/Ws7ke4Tjuy

**Comment by DrZoddiak** [comment]
The above PR addresses most links. The ones left are here:

Pending the update of DOJ Policy on Forums

___

 Government / Departments / Legal affairs / Jobs /  Protocols 

https://www.democracycraft.net/threads/employment-policy.11761/

**Comment by Technofied** [comment]
Technically this is resolved with the new wiki migration. :)
