### ISSUE TITLE
Train ticket in Reveille TPs you to the wrong place in Willow

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#85]
There's a train station in Reveille with a ticket system at XYZ: 4004.625 / 74 / 3523.132
When you right click the monitor and pick 'Willow station' it will tp you to the Wl-f032 plot instead of TPing you to spawn.

**Comment by adamloeffen** [comment]
**Issue:** Metro menu was warping players to location of old willow train station which was removed during the reconstruction of the ~~ex~~ town.
**Solution:** Set `train-willow` warp to the location of willow spawn.

**Comment by adamloeffen** [comment]
![Image](https://github.com/user-attachments/assets/f2b36085-9aa1-4f77-a3ca-0f273bb95c61)

**Comment by Nacholebraa** [comment]
Issue is resolved per update. //r
