### ISSUE TITLE
Update permissions to use modern conventions

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#86]
**Issue:** Permissions using `democracy.permission` notation are outdated and are to be replaced with an alternate, and more descriptive permission name. Commissioned by Tech.
**Example:** `democracy.ranger` would be broken down into different `doi.<permission>` permissions based on any given command. `doi.fly`, `doi.tp`, etc etc. Then all those permission are assigned to their respective groups along the DOI track.

**Comment by adamloeffen** [comment]
> [!NOTE]
> The following files have been modified in this fix:
> - `home/plugins/MyCommand/commands/department_of_commerce.yml`
> - `.../department_of_construction_and_transportation.yml`
> - `.../department_of_education.yml`
> - `.../department_of_health.yml`
> - `.../department_of_homeland_security.yml`
> - `.../department_of_justice.yml`
> - `.../department_of_public_affairs.yml`
> - `.../department_of_state.yml`
> - `.../department_of_the_interior.yml`
> - `.../server_staff.yml`

## DEPARTMENT OF COMMERCE
### PERMISSIONS TABLE
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /register-business-shoutout | `group.commercesec` | `doc.shoutout.business.register` |
| /register-campaign-shoutout | `group.commercesec` | `doc.shoutout.campaign.register` |
| /toggle-campaign-shoutout | `group.commercesec` | `doc.shoutout.campaign.toggle` |
| /treasury-processing | `democracy.console` | `console.dc` |
| /doc-mint | `group.commercesec` | `doc.mint` |
| /doc-broadcast | `group.commercesec` | `doc.broadcast.send` |
| /ad | `democracy.advertisement` | `doc.advertisement` |
| /doc-grant | `dec.grant` | `doc.grant` |
| /doc-cm-give | `group.economist` | `doc.business.create.give` |
| /doc-cm-revoke | `group.economist` | `doc.business.create.revoke` |
| /doc-listjobs | `democracy.owner` | `doc.listjobs` |
| /prune | `group.commercesec` | `doc.prune` |
| /reclaim-pruned | `NONE` | `doc.default.reclaim` |
| /billboard | `NONE` | `doc.default.billboard` |
| /doc-billboard-reset | `group.economist` | `doc.billboard.reset` |
| /doc-billboard-reject-funds | `group.economist` | `doc.billboard.reject.funds` |
| /doc-billboard-reject-image | `group.economist` | `doc.billboard.reject.image` |
| /doc-billboard-approve | `group.economist` | `doc.billboard.approve` |
| /pay | `NONE` | `doc.default.pay` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| commercesec | `doc.shoutout.*` `doc.mint` `doc.broadcast.*` `doc.grant` `doc.business.*` `doc.prune` `doc.billboard.*` |
| economist | `doc.grant` `doc.business.*` `doc.billboard.*` `doc.broadcast.recieve` |
| compliance officer | `doc.broadcast.recieve` |
| entrepreneur | `doc.advertisement` |
| default | `doc.default.*` |
| owner | `doc.listjobs` `console.dc` |
| senioradministrator | `console.dc` |
| systemadministrator | `console.dc` |

## DEPARTMENT OF CONSTRUCTION AND TRANSPORTATION
### PERMISSIONS TABLE
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /dct-eviction-notice | `dct.eviction-notice` | `dct.eviction.notice` |
| /dct-reset-plot-status | `dct.eviction-notice` | `dct.eviction.plot-status.reset` |
| /region-status | `NONE` | `dct.default.eviction-status` |
| //copy | `NONE` | `dct.worldedit.copy` |
| //paste | `NONE` | `dct.worldedit.paste` |
| //pa | `NONE` | `dct.worldedit.paste` |
| //schem load | `NONE` | `dct.worldedit.schematic` |
| /as tp | `NONE` | `dct.tp` |
| /dct-add-to-region | `dct.add-to-region` | `dct.regionadd` |
| /dct-broadcast | `group.constructionsec` | `dct.broadcast.send` |
| /dct-debugstick | `constructor` | `dct.debugstick` |
| /dct-tp | `democracy.BI` | `dct.tp` |
| /dct-bw-give-town | `dct.management` | `dct.playerbuildworld.give` |
| /dct-bw-revoke-town | `dct.management` | `dct.playerbuildworld.revoke` |
| /bw-get-debugstick | `playerbuildworldperms.debugstick` | `dct.playerbuildworld.debugstick` |
| /dct-creative | `group.constructor` | `dct.creative` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| constructionsec | `dct.eviction.*` `dct.worldedit.*` `dct.tp` `dct.region.*` `dct.broadcast.*` `dct.debugstick` `dct.playerbuildworld.*` `dct.creative` |
| constructionmanager | `dct.worldedit.*` `dct.tp` `dct.regionadd` `dct.debugstick` `dct.playerbuildworld.*` `dct.creative` `dct.broadcast.recieve` |
| constructor | `dct.worldedit.*` `dct.tp` `dct.regionadd` `dct.debugstick` `dct.creative` `broadcast.recieve` |
| inspectionmanager | `dct.eviction.*` `dct.tp` `dct.broadcast.recieve` |
| buildinginspector | `dct.eviction.*` `dct.tp` `dct.broadcast.recieve` |
| town-build-perms | `dct.playerbuildworld.debugstick` |
| default | `dct.default.*` |
| administrator | `dct.debugstick` |

## DEPARTMENT OF EDUCATION
### PERMISSIONS TABLE
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /doe-broadcast | `group.eductionsec` | `doe.broadcast.send` |
| /request-guide | `NONE` | `doe.default.request` |
| /doe-attend | `group.guide` | `doe.attend` |
| /quitjob | `NONE` | `doe.default.quitjob` |
| /quitprofession | `NONE` | `doe.default.quitjob` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| educationsec | `doe.broadcast.*` |
| educationmanager | `doe.broadcast.recieve` |
| archivemanager | `doe.broadcast.recieve` |
| tourmanager | `doe.broadcast.recieve` `doe.attend` |
| professor | `doe.broadcast.recieve` |
| archivist | `doe.broadcast.recieve` |
| guide | `doe.broadcast.recieve` `doe.attend` |
| default | `doe.default.*` |

## DEPARTMENT OF HEALTH
### PERMISSIONS TABLE
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /doh-broadcast | `group.healthsec` | `doh.broadcast.send` |
| /doh-revoke-doctor | `group.healthsec` | `doh.doctor.revoke` |
| /doh-unrevoke-doctor | `group.healthsec` | `doh.doctor.unrevoke` |
| /mcpaybroadcast | `console.dc` | `console.dc` |
| /request-a-doctor | `NONE` | `doh.default.request-a-doctor` |
| /emt | `NONE` | `doh.default.emt` |
| /doctor-attend | `democracy.attend` | `doh.attend` |
| /emt-attend | `democracy.attend` | `doh.emt-attend` |
| /doh-warp | `doh.medicalspecialist` | `doh.warp` |
| /doh-revoke-medicare | `group.healthsec` | `doh.medicare.revoke` |
| /doh-unrevoke-medicare | `group.healthsec` | `doh.medicare.unrevoke` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| healthsec | `doh.broadcast.*` `doh.doctor.*` `doh.attend` `doh.emt-attend` `doh.warp` `doh.medicare.*` |
| medicalspecialist | `doh.broadcast.recieve` `doh.attend` `doh.emt-attend` `doh.warp` |
| epidemiologist | `doh.broadcast.recieve` |
| paramedic | `doh.broadcast.recieve` `doh.emt-attend` |
| doctor | `doh.broadcast.recieve` `doh.attend` |
| traineedoctor | `doh.broadcast.recieve` `doh.attend` |
| pharmacist | `doh.broadcast.recieve` |
| default | `doh.default.*` |

## DEPARTMENT OF HOMELAND SECURITY
### PERMISSIONS TABLE
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /dhs-broadcast | `dhs.secretary` | `dhs.broadcast.send` |
| /consent | `NONE` | `dhs.default.consent` |
| /dhs-notify | `democracy.police` | `dhs.notify` |
| /unjail | `democracy.police` | `dhs.log.unjail` |
| /wanted remove | `democracy.police` | `dhs.log.remove.wanted` |
| /jail record remove | `democracy.police` | `dhs.log.remove.record` |
| /dhs-pullover | `democracy.police` | `dhs.driver.pullover` |
| /dhs-revoke-drivers | `dhs.revoke` | `dhs.driver.revoke` |
| /dhs-unrevoke-drivers | `dhs.revoke` | `dhs.driver.unrevoke` |
| /jail-reduce-time | `NONE` | `dhs.default.reduce-time` |
| /console-prison-pickaxe | `NONE` | `console.dc` |
| /wanted-notify | `NONE` | `console.dc` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| homelandsec | `dhs.broadcast.*` `dhs.notify` `dhs.log.*` `dhs.driver.*` |
| captain | `dhs.broadcast.recieve` `dhs.notify` `dhs.log.*` `dhs.driver.*` |
| lieutenant | `dhs.broadcast.recieve` `dhs.notify` `dhs.log.*` `dhs.driver.*` |
| sergeant | `dhs.broadcast.recieve` `dhs.notify` `dhs.log.*` `dhs.driver.*` |
| policeofficer | `dhs.broadcast.recieve` `dhs.notify` `dhs.log.*` `dhs.driver.*` |
| recruit | `dhs.broadcast.recieve` `dhs.notify` `dhs.log.*` `dhs.driver.*` |
| default | `dhs.default.*` |

## DEPARTMENT OF JUSTICE
### PERMISSIONS TABLE 
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /doj-broadcast | `doj.secretary` | `doj.broadcast.recieve` |
| /rba | `NONE` | `doj.default.rba` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| attorneygeneral | `doj.broadcast.*` |
| solicitorgeneral | `doj.broadcast.recieve` |
| investigationmanager | `doj.broadcast.recieve` |
| specialprosecutor | `doj.broadcast.recieve` |
| investigator | `doj.broadcast.recieve` |
| stateprosecutor | `doj.broadcast.recieve` |
| default | `doj.default.*` |

## DEPARTMENT OF PUBLIC AFFAIRS
### PERMISSIONS TABLE
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /dpa-broadcast | `dpa.secretary` | `dpa.broadcast.send` |
| /dpa-setevent | `group.eventmanager` | `dpa.setwarp` |
| /dpa-events | `democracy.dpa` | `dpa.eventsworld.warp` |
| /dpa-tph | `dpa.fly` | `dpa.tph` |
| /dpa-tp | `dpa.fly` | `dpa.tp` |
| /dpa-checkinventory | `dpa.fly` | `dpa.fly` |
| /dpa-reset-eventsworld | `group.publicaffairssec` `dpa.eventsworld.reset` |
| /blue-red-assign-a-team | `NONE` | `dpa.default.assign-color` |
| /red-spawn | `group.red` | `dpa.red-blue.red` |
| /blue-spawn | `group.blue` | `dpa.red-blue.blue` |
| /event | `NONE` | `dps.default.event` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| publicaffairssec | `dpa.broadcast.*` `dpa.setwarp` `dpa.eventsworld.*` `dpa.tph` `dpa.tp` `dpa.fly` `dpa.red-blue.*` |
| eventmanager | `dpa.broadcast.recieve` `dpa.setwarp` `dpa.eventsworld.warp` `dpa.tph` `dpa.tp` `dpa.fly` |
| mediamanager | `dpa.broadcast.recieve` |
| eventcoordinator | `dpa.broadcast.recieve` `dpa.eventsworld.warp` `dpa.tph` `dpa.tp` `dpa.fly` |
| mediaadvisor | `dpa.broadcast.recieve` |
| eventdesigner | `dpa.broadcast.recieve` `dpa.eventsworld.warp` `dpa.fly` |
| red | `dpa.red-blue.red` |
| blue | `dpa.red-blue.blue` |
| default | `dpa.default.*` |

## DEPARTMENT OF STATE
### PERMISSIONS TABLE
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /dos-broadcast | `dos.secretary` | `dos.broadcast.send` |
| /dos-census-reminder | `group.auditor` | `dos.census-reminder.send` |
| /dos-registervoter | `dos.electoralofficer` | `dos.registervoter` |
| /dos-requestregistration | `dos.requestregistration` | `dos.default.requestregistration` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| statesec | `dos.broadcast.*` |
| electionmanager | `dos.broadcast.recieve` `dos.registervoter` |
| electoralofficer | `dos.broadcast.recieve` |
| auditor | `dos.broadcast.recieve` `dos.census-reminder.send` |
| default | `dos.default.*` |

## DEPARTMENT OF THE INTERIOR
### PERMISSIONS TABLE
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /doi-broadcast | `democracy.console` | `doi.broadcast.send` |
| /doi-attend | `democracy.ranger` | `doi.attend` |
| /doi-tp | `democracy.ranger` | `doi.tp` |
| /doi-worldedit | `group.seniorranger` | `doi.worldedit` |
| /request-a-ranger | `NONE` | `doi.default.request-ranger` |
| /doi-unclaimed | `democracy.ranger` | `doi.mail.unclaimed` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| interiorsec | `doi.broadcast.*` `doi.attend` `doi.tp` `doi.worldedit` `doi.mail.*` |
| seniorranger | `doi.broadcast.receive` `doi.attend` `doi.tp` `doi.worldedit` `doi.mail.*` |
| supplymanager | `doi.broadcast.receive` |
| ranger | `doi.broadcast.receive` `doi.attend` `doi.tp` `doi.mail.*` |
| supplyofficer | `doi.broadcast.receive` |
| default | `doi.default.*` |

## STAFF
### PERMISSIONS TABLE
| Command | Original Permission | Modified Permission |
|--------|--------|--------|
| /migrate-coins | `NONE` | `staff.default.coins.migrate` |
| /staff-backend-prompt | `democracy.staff.backend` | `staff.backend.prompt` |
| /staff-vault | `democracy.staff` | `staff.vault` |
| /staff-notanalt | `democracy.staff` | `staff.alts.notanalt` |
| /staff-resources | `democracy.staff` | `staff.warp.resources` |
| /staff-alttest | `democracy.staff` | `staff.alts.alttest` |
| /staff-getfeather | `democracy.staff` | `staff.get.feather` |
| /staff-givefood | `democracy.administrator` | `staff.spawn.food` |
| /staff-nightvision | `democracy.staff` | `staff.nightvision` |
| /staff-sendtospawn | `democracy.staff` | `staff.sendtospawn` |
| /staff-xrayore-stone | `democracy.staff` | `staff.xrayore.stone` |
| /staff-xrayore-debris | `democracy.staff` | `staff.xrayore.debris` |
| /staff-xrayore-deepslate | `democracy.staff` | `staff.xrayore.deepslate` |
| //delwand | `democracy.staff` | `staff.worldedit.delwand` |
| /staff-sober` | `democracy.staff` | `staff.sober` |
| /staff-cleanup-locks | `staff.cleanup_locks` | `staff.locks.cleanup` |
| /staff-watchticket | `democracy.staff` | `staff.ticket.watch` |
| /next | `democracy.staff` | `staff.ticket.next` |
| /close | `democracy.staff` | `staff.ticket.close` |
| /staff-fixname-tier1 | `democracy.admin` | `staff.fixname.tier1` |
| /staff-fixname-tier2 | `democracy.admin` | `staff.fixname.tier2` |
| /staff-fixname-tier3 | `democracy.admin` | `staff.fixname.tier3` |
| /staff-fixname-tier4 | `democracy.admin` | `staff.fixname.tier4` |
| /staff-tp | `democracy.staff` | `staff.teleport.tp` |
| /staff-tpc | `democracy.staff` | `staff.teleport.tpc` |
| /staff-tph | `democracy.staff` | `staff.teleport.tph` |
| /staff-getwool | `democracy.staff` | `staff.get.wool` |
| /staff-getsign | `democracy.staff` | `staff.get.sign` |
| /staff-getchest | `democracy.staff` | `staff.get.chest` |
| /staff-getbarrel | `democracy.staff` | `staff.get.barrel` |
| /region-urban | `democracy.staff` | `staff.region.urban` |
| /regionn-wild | `democracy.staff` | `staff.region.wild` |
| /region-plot | `democracy.staff` | `staff.region.plot` |
| /region-delete | `democracy.staff` | `staff.region.delete` |
| /staff-force-local | `democracy.staff` | `staff.forcechannel.local` |
| /staff-force-global | `democracy.staff` | `staff.forcechannel.global` |
| /discord-fix-job-display | `NONE` | `staff.default.discord.fix-job-display` |
| /broadcast | `democracy.staff` | `staff.broadcast-to-server` |
| /staff-broadcast | `democracy.console` | `staff.broadcast.send` |
| /staff-gps-create | `democracy.staff` | `staff.gps.create` |
| /staff-gps-delete | `democracy.staff` | `staff.gps.delete` |
| /staff-killboat | `democracy.admin` | `staff.kill-entity.boat` |
| /punish | `democracy.staff` | `staff.punishplayer` |

### GROUPS TABLE
| Group | Permissions |
|-------|-------------|
| owner | `staff.*` |
| systemmanager | `staff.*` |
| manager | `staff.*` |
| systemadministrator | `staff.backend.*` `staff.warp.resources` `staff.get.*` `staff.spawn.*` `staff.nightvision` `staff.worldedit.*` `staff.sober` `staff.locks.cleanup` `staff.fixname.*` `staff.teleport.*` `staff.region.*` `staff.forcechannel.*` `staff.broadcast-to-server` `staff.broadcast.*` `staff.gps.*` `staff.kill-entity.*` `staff.fly` |
| senioradministrator | `staff.vault` `staff.alts.*` `staff.warp.*` `staff.get.*` `staff.spawn.*` `staff.nightvision` `staff.sendtospawn` `staff.xrayore.*` `staff.worldedit.*` `staff.sober` `staff.locks.*` `staff.ticket.*` `staff.fixname.*` `staff.teleport.*` `staff.region.*` `staff.forcechannel.*` `staff.broadcast-to-server` `staff.broadcast.*` `staff.gps.*` `staff.kill-entity.*` `staff.punishplayer` `staff.fly` |
| developer | `staff.broadcast.recieve` |
| configurator | `staff.broadcast.recieve` |
| administrator | `staff.vault` `staff.alts.*` `staff.warp.*` `staff.get.*` `staff.spawn.*` `staff.nightvision` `staff.sendtospawn` `staff.xrayore.*` `staff.worldedit.*` `staff.sober` `staff.locks.*` `staff.ticket.*` `staff.fixname.*` `staff.teleport.*` `staff.region.*` `staff.forcechannel.*` `staff.broadcast-to-server` `staff.broadcast.recieve` `staff.gps.*` `staff.kill-entity.*` `staff.punishplayer` `staff.fly` |
| moderator | `staff.vault` `staff.alts.notanalt` `staff.alts.alttest` `staff.get.wool` `staff.get.sign` `staff.get.chest` `staff.get.sign` `staff.get.barrel` `staff.get.feather` `staff.nightvision` `staff.sendtospawn` `staff.xrayore.*` `staff.worldedit.*` `staff.sober` `staff.locks.cleanup` `staff.ticket.next` `staff.ticket.close` `staff.teleport.tp` `staff.teleport.tpc` `staff.teleport.tph` `staff.region.urban` `staff.region.wild` `staff.region.plot` `staff.region.delete` `staff.forcechannel.local` `staff.forcechannel.global` `staff.gps.create` `staff.gps.delete` `staff.punishplayer` `staff.fly` |
| trialmoderator | `staff.vault` `staff.alts.notanalt` `staff.alts.alttest` `staff.get.wool` `staff.get.sign` `staff.get.chest` `staff.get.sign` `staff.get.barrel` `staff.get.feather` `staff.nightvision` `staff.sendtospawn` `staff.xrayore.*` `staff.worldedit.*` `staff.sober` `staff.locks.cleanup` `staff.ticket.next` `staff.ticket.close` `staff.teleport.tp` `staff.teleport.tpc` `staff.teleport.tph` `staff.region.urban` `staff.region.wild` `staff.region.plot` `staff.region.delete` `staff.forcechannel.local` `staff.forcechannel.global` `staff.gps.create` `staff.gps.delete` `staff.punishplayer` `staff.fly` |
| default | `staff.default.*` |

> [!IMPORTANT]  
> While working through these permission changes, I had to read the MyCommands files. Since I was there anyway, I figured I'd clean up a little, so I updated the headings of each file to include an accurate list of the commands they contain and moved the parts of the command around a little. (e.x. command -> type -> runcmd/text/both -> permission-required -> permission-node -> etc etc) just because I like the consistency 💀 The most important changes I made whilst cleaning (command name changes, disabling commands, etc etc) have been logged below :>
> - `/register-business-shoutout` -> `/doc-register-business-shoutout` [reason: department prefix added for ease of access/consistency]
> - `/register-campagin-shoutout` -> `/doc-register-campaign-shoutout` [reason: department prefix added for ease of access/consistency]
> - `/toggle-campaign-shoutout` -> `/doc-toggle-campaign-shoutout` [reason: department prefix added for ease of access/consistency]
> - `/prune` -> `/doc-prune` [reason: department prefix added for ease of access/consistency]
> - disabled `/towardsjail`, `/dhs-policeattend`, `/dhs-log-jail`  [reason: This was done at the request of the DHS Secretary, HellsideBurnton as these commands are all outdated/unused]
> - disabled `/request-tour-university`, `/dpa-tourend` [reason: outdated. DPA no longer handles tours and commands were unused]
> - migrated `/request-tour` to DOE file instead of DPA (there were copies in both) [reason: DOE now manages tours, instead of the DPA]
> - `/red-spawn` -> `/spawn-red` [reason: ease of access. will tab as an option when a player types "spawn"]
> - `/blue-spawn` -> `/spawn-blue` [reason: ease of access. will tab as an option when a player types "spawn"]
> - disabled `/dos-tph` [reason: we no longer recognize foreign ambassadors/relations + unused]
> - `/census-reminder` -> `/dos-census-reminder` [reason: department prefix added for ease of access/consistency]
> - `/sendtospawn` updated to actually send people to spawn as opposed to just acting like `/spawn`
> - `/sendtospawn` -> `/staff-sendtospawn` [reason: staff prefix added for ease of access/consistency]
> - disabled `/clearas` at Tech's request
> - disabled `/stp` and `/stph` and instead just added them to the `/staff-tp` and `/staff-tph` commands as aliases
> - Woolorama vote finally implemented. staff can pick different wool colors with `/staff-getwool` (doesn't need a color argument, but it's an option now)
> - `/staff-getign` commands compressed into one command block via a script for arguments. (doesn't need a color argument, but it's an option)
> - `/staff-channelforce-l` -> `/staff-force-local` [reason: the command was long and now it's shorter ¯\_(ツ)_/¯ ]
> - `/staff-fixcosmetics` disabled... we no longer use procosmetics
> - disabled `/staff-capswarning` as our chat filter takes care of that now
> - disabled `/cratepreview-seasonal`, `/cratepreview-supreme` and `/cratepreview-ultra` as the command was somewhat redundant with the default group being able to access `/crate preview <create-type>` anyway
> - also changed the permission node in the fly GUI to `staff.fly` instead of `democracy.staff`, unrelated to MyCommand.

**Comment by adamthewarrior** [comment]
(_Changes approved by Technofied._)

## ACTIONED LIST

- [ ] DOC
- [ ] DCT
- [ ] DOE
- [ ] DOH
- [ ] DHS
- [ ] DOJ
- [ ] DPA
- [ ] DOS
- [ ] DOI
- [ ] STAFF

**Comment by adamloeffen** [comment]
Actioned + Announced :> I won't close bc that's systems job but this one is all done

**Comment by Nacholebraa** [comment]
Updates look good closing thread. Thank you. <3
