### ISSUE TITLE
Speech bubbles not showing text

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#89]
Speech bubbles aren't always showing text above a player's head. You have to be at a certain angle to see it.

![Image](https://github.com/user-attachments/assets/01d07546-ebdd-4cad-ba57-19456272bb2a)

I swear I just saw this on the plugin's wiki the other day so I'll try to find it.

**Comment by taylorhaight** [comment]
Seems to only be sometimes but here's what I found. 

https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/common-questions#:~:text=Common%20Questions-,Q1%3A%20My%20nameplate/bubble%20are%20flickering%20%7C%20Background/Images%20has%20overlapping%20shadows,-This%20is%20a

**Comment by Technofied** [comment]
Fixed to the best of my ability. :)
