### ISSUE TITLE
/togglestream does not apply TAB suffix

### ISSUE THREAD

**Issue by Technofied** [MinecraftCitiesNetwork/Bugs#9]
This is because when I redone in-game prefixes and suffixes, the hacky Staff meta used no longer exists. Someone needs to implement this another way.

**Comment by adamloeffen** [comment]
### **Modified:**
- lines 129 and 132 in `home/plugins/MyCommand/commands/other.yml` to remove the staff prefix/suffix that the "Live" text used to use and replaced it with `%luckperms_meta_misc%`.
  - line 129 set the Live suffix and line 132 cleared the suffix

- lines 11 and 12 in `home/plugins/TAB/groups.yml` to create the new meta ("misc") to add and take away the live suffix
  - both lines were previously empty

**Comment by Technofied** [comment]
Great resolution, reviewed and accepted!
