### ISSUE TITLE
WorldGuard Issue - system-15567

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#93]
I've seen this issue before. The plot r097 used to be region like every other plot, excluding the plot dividers (leaves), but in actuality the player wouldn't be able to touch the edge of what is claimed by the WG regioning tool. For a temporary fix. What's weird is that once I expanded it to the plot divider (leaves) as a temporary fix, then the player was able to build inside their plot, but unfortunately they can also interact with the plot divider. It's a temporary fix.
The error the player gets is 'Sorry! You can't break that block here.'

**Comment by Nacholebraa** [comment]
Under review // pending player testing and re-regioning.

**Comment by Nacholebraa** [comment]
Reassigned to Tech for further resolution. 

Affected regions: **R097**, **or-conventioncenter**

**Comment by Technofied** [comment]
https://github.com/PaperMC/Paper/pull/11275

This Pull Request fixes it, but ItemsAdder won't let us boot on 1.21.1 💀 

**Temporary Resolution**
Go into creative, place blocks in the affected area(s), then break them. :)
