### ISSUE TITLE
Wrong link linked in /rules

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#94]
The /rules command shows you this link: "https://wiki.democracycraft.net/Rules/", 
instead it should show this link: "https://wiki.democracycraft.net/Rules"

![Image](https://github.com/user-attachments/assets/1e718959-fefc-4a01-adf1-01b4e1db96e9)

![Image](https://github.com/user-attachments/assets/98efc6dd-358c-4aea-b5f9-50dde7f46a02)

**Comment by Technofied** [comment]
Correct link, issue with web server resolved...

No matter how much documentation you feed AI, unfortunately intuition still is required :P 
`    @trailingSlash {
        path_regexp trailingSlash ^(.+)/$
    }
    redir @trailingSlash https://wiki.democracycraft.net{http.regexp.trailingSlash.1}`
