### ISSUE TITLE
Custom fishing - unable to sell radioactive fish

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#95]
Unable to sell radioactive fish to Larry the Fisher

![Image](https://github.com/user-attachments/assets/0e2bda22-3009-44fa-b2de-e55151976cb7)

**Comment by Technofied** [comment]
@crytiee Was this caught prior or after the update, and can you leave it in your inventory for me to have a look at later?

**Comment by crytiee** [comment]
@Technofied after and sure

**Comment by Technofied** [comment]
![Image](https://github.com/user-attachments/assets/11ed61f3-1817-422c-b5ef-5ac47516551b)

Apparently the plugin treats this as a form of rubbish, sorry
