### ISSUE TITLE
Server chat spotlight colors error

### ISSUE THREAD

**Issue by crytiee** [MinecraftCitiesNetwork/Bugs#97]
The color formatting here is inconsistent. 
'To find a job' should be cyan.

![Image](https://github.com/user-attachments/assets/2d720ed5-108c-43b8-8954-abd96588548b)

**Comment by adamloeffen** [comment]
> [!NOTE]
> The following file(s) was modified in this fix:
> - `home/plugins/AnnouncerPlus/message-configs/server-reminders.conf`

**Issue:** Color was formatted wrong in the server announcement.
**Solution:** Added a missing color tag to the message in line 111 to correct the color formatting.

**Original Line:**
```
            "<gradient:#00AAFF:#008EFF><bold>SERVER </bold></gradient> <color:#bdc3c7>»</color> <aqua>Get a job at <color:#008eff>/university, <aqua>then <color:#008eff>/findajob to find your exam room!",
```
**Modified Line:**
```
            "<gradient:#00AAFF:#008EFF><bold>SERVER </bold></gradient> <color:#bdc3c7>»</color> <aqua>Get a job at <color:#008eff>/university, <aqua>then <color:#008eff>/findajob <aqua>to find your exam room!",
```

**Comment by Technofied** [comment]
Running it in chat to test formatting, there is a 99.999999% chance this works (that 0.000000001% we can blame on End) (ok joking, just reopen if it is not solved though!)
